const STORAGE_KEY = 'contract-time-tracker-v1';
const SIDEBAR_WIDTH_KEY = 'contract-time-sidebar-width';
const defaultState = {
  contracts: [
    { id: 'meridian', name: 'Meridian House', number: 'CNT-1048', suffix: 'A-01', accumulated: 11700, startedAt: null, pinned: false },
    { id: 'northline', name: 'Northline Depot', number: 'CNT-0917', suffix: 'B-04', accumulated: 18900, startedAt: null, pinned: true },
    { id: 'harbour', name: 'Harbour Exchange', number: 'CNT-1182', suffix: 'C-02', accumulated: 4920, startedAt: null, pinned: false },
    { id: 'civic', name: 'Civic Centre Refurb', number: 'CNT-0974', suffix: 'A-03', accumulated: 27300, startedAt: null, pinned: false }
  ],
  nonWorking: [
    { id: 'nw-1', date: '2026-09-12', category: 'Break', start: '12:00', end: '12:30' },
    { id: 'nw-2', date: '2026-09-11', category: 'Annual leave', start: '09:00', end: '17:00' }
  ],
  order: ['meridian', 'northline', 'harbour', 'civic'],
  users: [{ id: 'jordan', name: 'Jordan Reed', start: '09:00', end: '17:00', breaks: [{ id: 'break-jordan', type: 'Break', start: '12:00', end: '12:30' }] }],
  breakState: null
};

let state = loadState();
let toastTimer;
const $ = (selector) => document.querySelector(selector);
state.users = state.users || structuredClone(defaultState.users);
state.breakState = state.breakState || null;
state.editSessions = state.editSessions || {};
const EDIT_TIMES_DATE = '2026-09-12';
state.contracts.forEach((contract, index) => { if (!state.editSessions[contract.id]) state.editSessions[contract.id] = [{ id: `session-${contract.id}-1`, date: EDIT_TIMES_DATE, start: minutesToTime(540 + index * 30), end: minutesToTime(570 + index * 30) }, { id: `session-${contract.id}-2`, date: EDIT_TIMES_DATE, start: minutesToTime(600 + index * 30), end: minutesToTime(660 + index * 30) }]; });
const savedSidebarWidth = Number(localStorage.getItem(SIDEBAR_WIDTH_KEY));
if (savedSidebarWidth >= 190 && savedSidebarWidth <= 360) document.documentElement.style.setProperty('--sidebar-width', `${savedSidebarWidth}px`);
const formatTime = (seconds, includeHours = true) => {
  const safeSeconds = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(safeSeconds / 3600).toString().padStart(2, '0');
  const minutes = Math.floor((safeSeconds % 3600) / 60).toString().padStart(2, '0');
  const remainder = (safeSeconds % 60).toString().padStart(2, '0');
  return includeHours ? `${hours}:${minutes}:${remainder}` : `${hours}:${minutes}`;
};
function loadState() { try { return { ...defaultState, ...JSON.parse(localStorage.getItem(STORAGE_KEY)) }; } catch { return structuredClone(defaultState); } }
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function contractSeconds(contract) { return contract.accumulated + (contract.startedAt ? Math.floor((Date.now() - contract.startedAt) / 1000) : 0); }
function nonWorkingSeconds(entry) { const [startHour, startMinute] = entry.start.split(':').map(Number); const [endHour, endMinute] = entry.end.split(':').map(Number); return Math.max(0, (endHour * 60 + endMinute - startHour * 60 - startMinute) * 60); }
function timeToMinutes(value) { const [hours, minutes] = value.split(':').map(Number); return hours * 60 + minutes; }
function minutesToTime(minutes) { return `${Math.floor(minutes / 60).toString().padStart(2, '0')}:${(minutes % 60).toString().padStart(2, '0')}`; }
function scheduleBreakSeconds(breakItem) { return Math.max(0, (timeToMinutes(breakItem.end) - timeToMinutes(breakItem.start)) * 60); }
function currentBreak() { const user = state.users.find((item) => item.id === 'jordan'); if (!user) return null; const now = new Date(); const minutes = now.getHours() * 60 + now.getMinutes(); return user.breaks.find((breakItem) => minutes >= timeToMinutes(breakItem.start) && minutes < timeToMinutes(breakItem.end)); }
function renderEditTimes() { const heading = $('#edit-timeline-heading'); if (!heading) return; heading.innerHTML = Array.from({ length: 24 }, (_, hour) => `<span>${hour.toString().padStart(2, '0')}:00</span>`).join(''); const date = $('#edit-times-date').value; const rows = $('#edit-time-rows'); rows.innerHTML = state.contracts.map((contract) => editContractTemplate(contract, date)).join(''); rows.querySelectorAll('.edit-session-handle').forEach(enableEditSessionHandle); }
function editContractTemplate(contract, date) { const sessions = (state.editSessions[contract.id] || []).filter((session) => session.date === date); return `<div class="schedule-row edit-session-row"><div class="user-cell"><div class="user-name-line"><strong>${contract.name}</strong><span class="edit-contract-code">${contract.number}</span></div></div><div class="timeline-lane">${sessions.map((session) => { const start = timeToMinutes(session.start); const end = timeToMinutes(session.end); return `<div class="scheduled-block edit-session-block" style="left:${start / 1440 * 100}%;width:${Math.max(1, end - start) / 1440 * 100}%" title="${session.start} - ${session.end}"><button class="schedule-handle start-handle edit-session-handle" data-contract-id="${contract.id}" data-session-id="${session.id}" data-handle="start" type="button" aria-label="Adjust ${contract.name} start time"></button><button class="schedule-handle end-handle edit-session-handle" data-contract-id="${contract.id}" data-session-id="${session.id}" data-handle="end" type="button" aria-label="Adjust ${contract.name} end time"></button></div>`; }).join('')}</div></div>`; }
function enableEditSessionHandle(handle) { let resizing = false; let startX; let originalStart; let originalEnd; const sessions = state.editSessions[handle.dataset.contractId]; const sessionIndex = sessions.findIndex((session) => session.id === handle.dataset.sessionId); const session = sessions[sessionIndex]; handle.addEventListener('pointerdown', (event) => { event.preventDefault(); resizing = true; startX = event.clientX; originalStart = timeToMinutes(session.start); originalEnd = timeToMinutes(session.end); handle.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); updateDragTooltip(handle, session, event); }); handle.addEventListener('pointermove', (event) => { if (!resizing) return; const lane = handle.closest('.timeline-lane'); const delta = Math.round(((event.clientX - startX) / lane.getBoundingClientRect().width * 1440) / 5) * 5; if (handle.dataset.handle === 'start') { session.start = minutesToTime(Math.min(originalEnd - 5, Math.max(0, originalStart + delta))); if (sessionIndex > 0) sessions[sessionIndex - 1].end = session.start; } else { session.end = minutesToTime(Math.max(originalStart + 5, Math.min(1440, originalEnd + delta))); if (sessionIndex < sessions.length - 1) sessions[sessionIndex + 1].start = session.end; } const block = handle.closest('.scheduled-block'); block.style.left = `${timeToMinutes(session.start) / 1440 * 100}%`; block.style.width = `${Math.max(1, timeToMinutes(session.end) - timeToMinutes(session.start)) / 1440 * 100}%`; updateDragTooltip(handle, session, event); }); handle.addEventListener('pointerup', (event) => { if (!resizing) return; resizing = false; handle.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); hideDragTooltip(); saveState(); renderEditTimes(); }); }
function renderContracts() {
  const sort = $('#sort-contracts').value;
  let contracts = state.order.map((id) => state.contracts.find((contract) => contract.id === id)).filter(Boolean);
  if (sort === 'active') contracts.sort((a, b) => Number(Boolean(b.startedAt)) - Number(Boolean(a.startedAt)));
  if (sort === 'name') contracts.sort((a, b) => a.name.localeCompare(b.name));
  $('#contract-grid').innerHTML = contracts.length ? contracts.map(contractTemplate).join('') : '<div class="empty-dashboard">No contracts on your dashboard yet. Add one to get started.</div>';
  document.querySelectorAll('.clock-button').forEach((button) => button.addEventListener('click', () => toggleClock(button.dataset.id)));
  document.querySelectorAll('.pin-action').forEach((button) => button.addEventListener('click', () => togglePin(button.dataset.id)));
  document.querySelectorAll('.delete-contract').forEach((button) => button.addEventListener('click', () => removeContract(button.dataset.id)));
  document.querySelectorAll('.tile').forEach(enableDrag);
  updateMetrics();
}
function contractTemplate(contract) { const running = Boolean(contract.startedAt); return `<article class="tile ${contract.pinned ? 'is-pinned' : ''}" draggable="${!contract.pinned}" data-id="${contract.id}"><div class="tile-header"><div class="tile-contract"><strong>${contract.name}</strong><span>${contract.number} / Suffix ${contract.suffix}</span></div><div class="tile-actions"><button class="tile-action pin-action" data-id="${contract.id}" title="${contract.pinned ? 'Unpin tile' : 'Pin tile'}" aria-label="${contract.pinned ? 'Unpin tile' : 'Pin tile'}">&#128205;</button><button class="tile-action delete-contract" data-id="${contract.id}" title="Remove contract" aria-label="Remove contract">&times;</button><span class="drag-handle" title="Drag to arrange">&#10303;</span></div></div><div class="tile-image">Image placeholder</div><div class="tile-times"><div class="time-block"><span>Accumulated</span><strong>${formatTime(contractSeconds(contract))}</strong></div><div class="time-block"><span>Current session</span><strong class="${running ? 'live-time' : ''}" data-live-id="${contract.id}">${running ? formatTime(Math.floor((Date.now() - contract.startedAt) / 1000)) : '00:00:00'}</strong></div></div><div class="tile-footer"><span class="tile-user">Jordan Reed</span><button class="clock-button ${running ? 'is-running' : ''}" data-id="${contract.id}" type="button">${running ? 'Stop clock' : 'Start clock'}</button></div></article>`; }
function toggleClock(id) { const contract = state.contracts.find((item) => item.id === id); if (!contract) return; if (contract.startedAt) { contract.accumulated += Math.floor((Date.now() - contract.startedAt) / 1000); contract.startedAt = null; showToast(`${contract.name} stopped and saved`); } else { const runningContract = state.contracts.find((item) => item.id !== id && item.startedAt); if (runningContract) { runningContract.accumulated += Math.floor((Date.now() - runningContract.startedAt) / 1000); runningContract.startedAt = null; } contract.startedAt = Date.now(); showToast(runningContract ? `${runningContract.name} stopped; ${contract.name} is now running` : `${contract.name} is now running`); } saveState(); renderContracts(); }
function togglePin(id) { const contract = state.contracts.find((item) => item.id === id); contract.pinned = !contract.pinned; saveState(); renderContracts(); showToast(contract.pinned ? 'Tile pinned in place' : 'Tile can be rearranged'); }
function removeContract(id) { state.contracts = state.contracts.filter((contract) => contract.id !== id); state.order = state.order.filter((contractId) => contractId !== id); saveState(); renderContracts(); showToast('Contract removed from dashboard'); }
function updateMetrics() { const total = state.contracts.reduce((sum, contract) => sum + contractSeconds(contract), 0); const active = state.contracts.filter((contract) => contract.startedAt).length; const nonWorking = state.users.reduce((sum, user) => sum + user.breaks.reduce((breakTotal, breakItem) => breakTotal + scheduleBreakSeconds(breakItem), 0), 0); const activeCount = $('#active-count'); $('#tracked-total').textContent = formatTime(total); if (activeCount) activeCount.textContent = active; $('#non-working-total').textContent = formatTime(nonWorking, false); }
function enableDrag(tile) { tile.addEventListener('dragstart', () => tile.classList.add('is-dragging')); tile.addEventListener('dragend', () => { tile.classList.remove('is-dragging'); const ids = [...document.querySelectorAll('.tile')].map((item) => item.dataset.id); state.order = ids.concat(state.order.filter((id) => !ids.includes(id))); saveState(); }); tile.addEventListener('dragover', (event) => { event.preventDefault(); const dragging = document.querySelector('.is-dragging'); if (dragging && dragging !== tile) { const box = tile.getBoundingClientRect(); tile.parentNode.insertBefore(dragging, event.clientY < box.top + box.height / 2 ? tile : tile.nextSibling); } }); }
function renderWorkingTimes() { const heading = $('#timeline-heading'); heading.innerHTML = Array.from({ length: 24 }, (_, hour) => `<span>${hour.toString().padStart(2, '0')}:00</span>`).join(''); const rows = $('#working-time-rows'); $('#empty-state').classList.toggle('is-hidden', state.users.length > 0); rows.innerHTML = state.users.map(userTemplate).join(''); rows.querySelectorAll('[data-user-field]').forEach((input) => input.addEventListener('change', () => { const user = state.users.find((item) => item.id === input.dataset.userId); user[input.dataset.userField] = input.value; saveState(); renderWorkingTimes(); updateMetrics(); })); rows.querySelectorAll('.remove-user').forEach((button) => button.addEventListener('click', () => removeUser(button.dataset.userId))); rows.querySelectorAll('.edit-break').forEach((button) => { button.addEventListener('click', () => { if (button.dataset.longPressed) { delete button.dataset.longPressed; return; } openScheduleModal(button.dataset.userId, button.dataset.breakId); }); enableBreakLongPress(button); }); rows.querySelectorAll('.add-break').forEach((button) => button.addEventListener('click', () => openScheduleModal(button.dataset.userId))); rows.querySelectorAll('.schedule-handle').forEach(enableScheduleHandle); }
function enableBreakLongPress(breakBlock) { let pressTimer; let longPressed = false; const cancelPress = () => { clearTimeout(pressTimer); }; breakBlock.addEventListener('pointerdown', (event) => { if (event.target.closest('.schedule-handle')) return; longPressed = false; pressTimer = setTimeout(() => { longPressed = true; if (window.confirm('Delete this break?')) deleteBreak(breakBlock.dataset.userId, breakBlock.dataset.breakId); else breakBlock.dataset.longPressed = 'true'; }, 700); }); breakBlock.addEventListener('pointerup', () => { clearTimeout(pressTimer); if (longPressed) breakBlock.dataset.longPressed = 'true'; }); breakBlock.addEventListener('pointerleave', cancelPress); breakBlock.addEventListener('pointercancel', cancelPress); }
function deleteBreak(userId, breakId) { const user = state.users.find((item) => item.id === userId); if (!user) return; user.breaks = user.breaks.filter((breakItem) => breakItem.id !== breakId); saveState(); renderWorkingTimes(); updateMetrics(); showToast('Break deleted'); }
function updateDragTooltip(handle, target, event) { const tooltip = $('#drag-tooltip'); tooltip.textContent = `${handle.dataset.handle === 'start' ? 'Start' : 'End'}: ${target[handle.dataset.handle]}`; tooltip.style.left = `${event.clientX + 12}px`; tooltip.style.top = `${event.clientY - 38}px`; tooltip.classList.remove('is-hidden'); }
function hideDragTooltip() { $('#drag-tooltip').classList.add('is-hidden'); }
function enableScheduleHandle(handle) { let resizing = false; let startX; let originalStart; let originalEnd; const user = state.users.find((item) => item.id === handle.dataset.userId); const breakItem = user?.breaks.find((item) => item.id === handle.dataset.breakId); const target = breakItem || user; handle.title = `Drag to adjust ${handle.dataset.handle} time`; handle.addEventListener('pointerdown', (event) => { event.preventDefault(); event.stopPropagation(); resizing = true; startX = event.clientX; originalStart = timeToMinutes(target.start); originalEnd = timeToMinutes(target.end); handle.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); updateDragTooltip(handle, target, event); }); handle.addEventListener('pointermove', (event) => { if (!resizing) return; const lane = handle.closest('.timeline-lane'); const delta = Math.round(((event.clientX - startX) / lane.getBoundingClientRect().width * 1440) / 5) * 5; if (handle.dataset.handle === 'start') target.start = minutesToTime(Math.min(originalEnd - 5, Math.max(0, originalStart + delta))); else target.end = minutesToTime(Math.max(originalStart + 5, Math.min(1440, originalEnd + delta))); const block = handle.closest(breakItem ? '.break-block' : '.scheduled-block'); const start = timeToMinutes(target.start); const end = timeToMinutes(target.end); block.style.left = `${start / 1440 * 100}%`; block.style.width = `${Math.max(0, end - start) / 1440 * 100}%`; if (!breakItem) { const row = handle.closest('.schedule-row'); row.querySelector(`[data-user-field="start"]`).value = target.start; row.querySelector(`[data-user-field="end"]`).value = target.end; } updateDragTooltip(handle, target, event); }); handle.addEventListener('pointerup', (event) => { if (!resizing) return; resizing = false; handle.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); hideDragTooltip(); saveState(); renderWorkingTimes(); updateMetrics(); }); handle.addEventListener('pointercancel', () => { if (!resizing) return; resizing = false; document.body.classList.remove('is-resizing'); hideDragTooltip(); }); }
function userTemplate(user) { const start = timeToMinutes(user.start); const end = timeToMinutes(user.end); const workWidth = Math.max(0, end - start) / 1440 * 100; return `<div class="schedule-row"><div class="user-cell"><div class="user-name-line"><strong>${user.name}</strong><button class="remove-user" data-user-id="${user.id}" type="button" title="Remove ${user.name}" aria-label="Remove ${user.name}">&times;</button></div><span><input type="time" data-user-id="${user.id}" data-user-field="start" value="${user.start}"> - <input type="time" data-user-id="${user.id}" data-user-field="end" value="${user.end}"></span><button class="add-break" data-user-id="${user.id}" type="button" title="Add a break for ${user.name}">+ break</button></div><div class="timeline-lane"><div class="scheduled-block" style="left:${start / 1440 * 100}%;width:${workWidth}%"><button class="schedule-handle start-handle" data-user-id="${user.id}" data-handle="start" type="button" title="Drag to adjust start time" aria-label="Adjust ${user.name} start time"></button><button class="schedule-handle end-handle" data-user-id="${user.id}" data-handle="end" type="button" title="Drag to adjust end time" aria-label="Adjust ${user.name} end time"></button></div>${user.breaks.map((breakItem) => `<div class="break-block edit-break" data-user-id="${user.id}" data-break-id="${breakItem.id}" style="left:${timeToMinutes(breakItem.start) / 1440 * 100}%;width:${Math.max(1, timeToMinutes(breakItem.end) - timeToMinutes(breakItem.start)) / 1440 * 100}%" title="Edit ${breakItem.type}: ${breakItem.start} - ${breakItem.end}"><button class="schedule-handle start-handle break-handle" data-user-id="${user.id}" data-break-id="${breakItem.id}" data-handle="start" type="button" title="Drag to adjust break start time" aria-label="Adjust ${breakItem.type} start time"></button><button class="schedule-handle end-handle break-handle" data-user-id="${user.id}" data-break-id="${breakItem.id}" data-handle="end" type="button" title="Drag to adjust break end time" aria-label="Adjust ${breakItem.type} end time"></button></div>`).join('')}</div></div>`; }
function overtimeLabel(user) { const start = timeToMinutes(user.start); const end = timeToMinutes(user.end); return start === end ? 'No scheduled hours' : `Overtime before ${user.start} / after ${user.end}`; }
function removeUser(id) { if (id === 'jordan') { showToast('Jordan Reed is the signed-in user'); return; } state.users = state.users.filter((user) => user.id !== id); saveState(); renderWorkingTimes(); updateMetrics(); showToast('User removed'); }
let editingScheduleUserId = null;
let editingScheduleBreakId = null;
function openContractModal() { $('#contract-modal').classList.remove('is-hidden'); $('#contract-name').focus(); }
function openScheduleModal(userId = null, breakId = null) { editingScheduleUserId = userId; editingScheduleBreakId = breakId; const user = state.users.find((item) => item.id === userId); const breakItem = user?.breaks.find((item) => item.id === breakId); $('#schedule-modal-title').textContent = user ? `Edit ${user.name}` : 'Add user'; $('#schedule-user-name').value = user?.name || ''; $('#schedule-start').value = user?.start || '06:00'; $('#schedule-end').value = user?.end || '15:00'; $('#schedule-break-start').value = breakItem?.start || '12:30'; $('#schedule-break-end').value = breakItem?.end || '13:05'; $('#schedule-modal').classList.remove('is-hidden'); $('#schedule-user-name').focus(); }
function closeScheduleModal() { $('#schedule-modal').classList.add('is-hidden'); $('#schedule-form').reset(); editingScheduleUserId = null; editingScheduleBreakId = null; }
function saveSchedule(event) { event.preventDefault(); const formData = new FormData(event.currentTarget); const name = formData.get('name').trim(); const start = formData.get('start'); const end = formData.get('end'); const breakStart = formData.get('breakStart'); const breakEnd = formData.get('breakEnd'); if (timeToMinutes(end) <= timeToMinutes(start) || timeToMinutes(breakEnd) <= timeToMinutes(breakStart)) { showToast('End times must be after start times'); return; } const user = editingScheduleUserId ? state.users.find((item) => item.id === editingScheduleUserId) : { id: `user-${Date.now()}`, name: '', start: '', end: '', breaks: [] }; user.name = name; user.start = start; user.end = end; if (editingScheduleBreakId) { const breakItem = user.breaks.find((item) => item.id === editingScheduleBreakId); breakItem.start = breakStart; breakItem.end = breakEnd; } else { user.breaks.push({ id: `break-${Date.now()}`, type: 'Break', start: breakStart, end: breakEnd }); } if (!editingScheduleUserId) state.users.push(user); saveState(); renderWorkingTimes(); updateMetrics(); closeScheduleModal(); showToast(editingScheduleUserId ? 'Working times updated' : 'User added to working times'); }
function closeContractModal() { $('#contract-modal').classList.add('is-hidden'); $('#contract-form').reset(); }
function addContract(event) { event.preventDefault(); const formData = new FormData(event.currentTarget); const name = formData.get('name').trim(); const number = formData.get('number').trim(); const suffix = formData.get('suffix').trim(); const id = `contract-${Date.now()}`; state.contracts.push({ id, name, number, suffix, accumulated: 0, startedAt: null, pinned: false }); state.order.push(id); state.editSessions[id] = [{ id: `session-${id}-1`, date: EDIT_TIMES_DATE, start: '09:00', end: '09:30' }]; saveState(); renderContracts(); renderEditTimes(); closeContractModal(); showToast('Contract added to dashboard'); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('is-visible'), 2300); }
function resetLayout() { state.order = defaultState.order.slice(); saveState(); renderContracts(); showToast('Tile layout reset'); }
function commitContract(contract) { if (!contract?.startedAt) return; contract.accumulated += Math.floor((Date.now() - contract.startedAt) / 1000); contract.startedAt = null; }
function handleBreakState() { const breakItem = currentBreak(); if (breakItem && !state.breakState) { const runningContract = state.contracts.find((contract) => contract.startedAt); if (runningContract) { commitContract(runningContract); state.breakState = { contractId: runningContract.id }; saveState(); showToast(`${runningContract.name} paused for break`); } } else if (!breakItem && state.breakState) { const pausedContract = state.contracts.find((contract) => contract.id === state.breakState.contractId); if (pausedContract && !state.contracts.some((contract) => contract.startedAt)) { pausedContract.startedAt = Date.now(); showToast(`${pausedContract.name} resumed after break`); } state.breakState = null; saveState(); } }
function tick() { handleBreakState(); state.contracts.filter((contract) => contract.startedAt).forEach((contract) => { const live = document.querySelector(`[data-live-id="${contract.id}"]`); if (live) live.textContent = formatTime(Math.floor((Date.now() - contract.startedAt) / 1000)); }); updateMetrics(); }
document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('is-active', item === button)); document.querySelectorAll('[data-view-panel]').forEach((panel) => panel.classList.toggle('is-hidden', panel.dataset.viewPanel !== button.dataset.view)); }));
$('#add-contract').addEventListener('click', openContractModal); $('#contract-form').addEventListener('submit', addContract); $('#close-contract-modal').addEventListener('click', closeContractModal); $('#cancel-contract').addEventListener('click', closeContractModal); $('#contract-modal').addEventListener('click', (event) => { if (event.target.id === 'contract-modal') closeContractModal(); }); $('#add-user').addEventListener('click', () => openScheduleModal()); $('#schedule-form').addEventListener('submit', saveSchedule); $('#close-schedule-modal').addEventListener('click', closeScheduleModal); $('#cancel-schedule').addEventListener('click', closeScheduleModal); $('#schedule-modal').addEventListener('click', (event) => { if (event.target.id === 'schedule-modal') closeScheduleModal(); }); $('#edit-times-date').addEventListener('change', renderEditTimes); $('#reset-layout').addEventListener('click', resetLayout); $('#sort-contracts').addEventListener('change', renderContracts);
const sidebarResize = $('.sidebar-resize'); let resizeStartX; let resizeStartWidth;
sidebarResize.addEventListener('pointerdown', (event) => { resizeStartX = event.clientX; resizeStartWidth = $('.sidebar').getBoundingClientRect().width; sidebarResize.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); });
sidebarResize.addEventListener('pointermove', (event) => { if (!sidebarResize.hasPointerCapture(event.pointerId)) return; const width = Math.min(360, Math.max(190, resizeStartWidth + event.clientX - resizeStartX)); document.documentElement.style.setProperty('--sidebar-width', `${width}px`); localStorage.setItem(SIDEBAR_WIDTH_KEY, width); });
sidebarResize.addEventListener('pointerup', (event) => { sidebarResize.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); });
renderContracts(); renderWorkingTimes(); renderEditTimes(); setInterval(tick, 1000);
