const STORAGE_KEY = 'contract-time-tracker-v2';
const SIDEBAR_WIDTH_KEY = 'contract-time-sidebar-width';
const defaultState = {
  contracts: [
    { id: 'meridian', customerName: 'Meridian House', number: 'CNT-1048', suffix: 'A-01', suffixDescription: '', machineType: '', image: null, accumulated: 11700, startedAt: null, pinned: false, hidden: false },
    { id: 'northline', customerName: 'Northline Depot', number: 'CNT-0917', suffix: 'B-04', suffixDescription: '', machineType: '', image: null, accumulated: 18900, startedAt: null, pinned: true, hidden: false },
    { id: 'harbour', customerName: 'Harbour Exchange', number: 'CNT-1182', suffix: 'C-02', suffixDescription: '', machineType: '', image: null, accumulated: 4920, startedAt: null, pinned: false, hidden: false },
    { id: 'civic', customerName: 'Civic Centre Refurb', number: 'CNT-0974', suffix: 'A-03', suffixDescription: '', machineType: '', image: null, accumulated: 27300, startedAt: null, pinned: false, hidden: false }
  ],
  nonWorking: [
    { id: 'nw-1', date: '2026-09-12', category: 'Break', start: '12:00', end: '12:30' },
    { id: 'nw-2', date: '2026-09-11', category: 'Annual leave', start: '09:00', end: '17:00' }
  ],
  machineTypes: ['Excavator', 'Dumper truck', 'Roller', 'Crane'],
  order: ['meridian', 'northline', 'harbour', 'civic'],
  users: [{ id: 'jordan', name: 'Jordan Reed', start: '09:00', end: '17:00', breaks: [{ id: 'break-jordan', type: 'Break', start: '12:00', end: '12:30' }] }],
  breakState: null
};

let state = loadState();
let toastTimer;
const $ = (selector) => document.querySelector(selector);
state.users = state.users || structuredClone(defaultState.users);
state.machineTypes = state.machineTypes || structuredClone(defaultState.machineTypes);
state.contracts.forEach((contract) => { if (contract.customerName === undefined) contract.customerName = contract.description ?? contract.name ?? ''; delete contract.description; delete contract.name; contract.customerName = (contract.customerName || '').toUpperCase(); contract.number = (contract.number || '').toUpperCase(); contract.suffix = (contract.suffix || '').toUpperCase(); contract.suffixDescription = (contract.suffixDescription || '').toUpperCase(); });
state.breakState = state.breakState || null;
state.editSessions = state.editSessions || {};
const EDIT_TIMES_DATE = '2026-09-12';
if (!Object.keys(state.editSessions).length) {
  const rotation = state.contracts.map((contract) => contract.id);
  for (let minutes = 360, i = 0; minutes < 900; minutes += 60, i += 1) {
    const contractId = rotation[i % rotation.length];
    const sessions = state.editSessions[contractId] || (state.editSessions[contractId] = []);
    sessions.push({ id: `session-${contractId}-${sessions.length + 1}`, date: EDIT_TIMES_DATE, start: minutesToTime(minutes), end: minutesToTime(minutes + 60) });
  }
}
const savedSidebarWidth = Number(localStorage.getItem(SIDEBAR_WIDTH_KEY));
if (savedSidebarWidth >= 190 && savedSidebarWidth <= 360) document.documentElement.style.setProperty('--sidebar-width', `${savedSidebarWidth}px`);
const formatTime = (seconds, includeHours = true) => {
  const safeSeconds = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(safeSeconds / 3600).toString().padStart(2, '0');
  const minutes = Math.floor((safeSeconds % 3600) / 60).toString().padStart(2, '0');
  const remainder = (safeSeconds % 60).toString().padStart(2, '0');
  return includeHours ? `${hours}:${minutes}:${remainder}` : `${hours}:${minutes}`;
};
function loadState() { try { return { ...defaultState, ...JSON.parse(localStorage.getItem(STORAGE_KEY)) }; } catch { return structuredClone(defaultState); } }
function saveState() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); return true; } catch (error) { return false; } }
function contractSeconds(contract) { return contract.accumulated + (contract.startedAt ? Math.floor((Date.now() - contract.startedAt) / 1000) : 0); }
function nonWorkingSeconds(entry) { const [startHour, startMinute] = entry.start.split(':').map(Number); const [endHour, endMinute] = entry.end.split(':').map(Number); return Math.max(0, (endHour * 60 + endMinute - startHour * 60 - startMinute) * 60); }
function timeToMinutes(value) { const [hours, minutes] = value.split(':').map(Number); return hours * 60 + minutes; }
function minutesToTime(minutes) { return `${Math.floor(minutes / 60).toString().padStart(2, '0')}:${(minutes % 60).toString().padStart(2, '0')}`; }
function scheduleBreakSeconds(breakItem) { return Math.max(0, (timeToMinutes(breakItem.end) - timeToMinutes(breakItem.start)) * 60); }
function currentBreak() { const user = state.users.find((item) => item.id === 'jordan'); if (!user) return null; const now = new Date(); const minutes = now.getHours() * 60 + now.getMinutes(); return user.breaks.find((breakItem) => minutes >= timeToMinutes(breakItem.start) && minutes < timeToMinutes(breakItem.end)); }
function sessionsForDate(date) { const list = []; state.contracts.forEach((contract) => { (state.editSessions[contract.id] || []).forEach((session) => { if (session.date === date) list.push({ contractId: contract.id, session }); }); }); list.sort((a, b) => timeToMinutes(a.session.start) - timeToMinutes(b.session.start)); return list; }
// EXPERIMENTAL — session unlink/relink via long-press on an Edit Times bar. To remove this feature: delete
// nearestLinkedSession, enableSessionLongPress, toggleSessionLink; the "session.unlinked ? ..." conditions in
// enableEditSessionHandle and editContractTemplate's block markup; the enableSessionLongPress wiring in
// renderEditTimes; and the .is-unlinked rule in styles.css.
function nearestLinkedSession(daySessions, index, step) { for (let i = index + step; i >= 0 && i < daySessions.length; i += step) { if (!daySessions[i].session.unlinked) return daySessions[i].session; } return undefined; }
function toggleSessionLink(contractId, sessionId) { const sessions = state.editSessions[contractId]; const session = sessions?.find((item) => item.id === sessionId); if (!session) return; if (session.unlinked) { const daySessions = sessionsForDate(session.date); const idx = daySessions.findIndex((entry) => entry.session.id === sessionId); const prev = daySessions[idx - 1]?.session; const next = daySessions[idx + 1]?.session; if (prev) session.start = prev.end; if (next) session.end = next.start; session.unlinked = false; showToast('Session linked to nearest times'); } else { session.unlinked = true; showToast('Session unlinked — drag it without affecting neighbours'); } saveState(); renderEditTimes(); }
function removeSession(contractId, sessionId) { const sessions = state.editSessions[contractId]; if (!sessions) return; showConfirm('Remove this time block?').then((confirmed) => { if (!confirmed) return; state.editSessions[contractId] = sessions.filter((item) => item.id !== sessionId); saveState(); renderEditTimes(); showToast('Time block removed'); }); }
function enableSessionLongPress(block) { let pressTimer; const cancelPress = () => clearTimeout(pressTimer); block.addEventListener('pointerdown', (event) => { if (event.target.closest('.schedule-handle')) return; pressTimer = setTimeout(() => toggleSessionLink(block.dataset.contractId, block.dataset.sessionId), 700); }); block.addEventListener('pointerup', cancelPress); block.addEventListener('pointerleave', cancelPress); block.addEventListener('pointercancel', cancelPress); }
function renderEditTimes() { const heading = $('#edit-timeline-heading'); if (!heading) return; heading.innerHTML = Array.from({ length: 24 }, (_, hour) => `<span>${hour.toString().padStart(2, '0')}:00</span>`).join(''); const date = $('#edit-times-date').value; const rows = $('#edit-time-rows'); const daySessions = sessionsForDate(date); const firstStart = {}; daySessions.forEach(({ contractId, session }) => { if (!(contractId in firstStart)) firstStart[contractId] = timeToMinutes(session.start); }); const sortedContracts = state.contracts.slice().sort((a, b) => (firstStart[a.id] ?? Infinity) - (firstStart[b.id] ?? Infinity)); rows.innerHTML = sortedContracts.map((contract) => editContractTemplate(contract, date)).join('') + editBreakBandsTemplate(); rows.querySelectorAll('.edit-session-handle').forEach((handle) => enableEditSessionHandle(handle, daySessions)); rows.querySelectorAll('.edit-session-block').forEach((block) => { enableSessionLongPress(block); block.addEventListener('dblclick', (event) => { if (event.target.closest('.schedule-handle')) return; removeSession(block.dataset.contractId, block.dataset.sessionId); }); }); }
function editBreakBandsTemplate() { const user = state.users.find((item) => item.id === 'jordan'); if (!user || !user.breaks.length) return ''; return `<div class="edit-break-overlay">${user.breaks.map((breakItem) => { const start = timeToMinutes(breakItem.start); const end = timeToMinutes(breakItem.end); return `<div class="edit-break-band" style="left:${start / 1440 * 100}%;width:${Math.max(1, end - start) / 1440 * 100}%" title="${breakItem.type}: ${breakItem.start} - ${breakItem.end}"></div>`; }).join('')}</div>`; }
function editContractTemplate(contract, date) { const sessions = (state.editSessions[contract.id] || []).filter((session) => session.date === date); return `<div class="schedule-row edit-session-row"><div class="user-cell edit-contract-cell"><div class="edit-contract-top"><strong>${contract.customerName}</strong><span class="edit-contract-code">${contract.number}</span></div><span class="edit-contract-code">${contract.suffix}${contract.suffixDescription ? ` | ${contract.suffixDescription}` : ''}</span></div><div class="timeline-lane">${sessions.map((session) => { const start = timeToMinutes(session.start); const end = timeToMinutes(session.end); return `<div class="scheduled-block edit-session-block ${session.unlinked ? 'is-unlinked' : ''}" data-contract-id="${contract.id}" data-session-id="${session.id}" style="left:${start / 1440 * 100}%;width:${Math.max(1, end - start) / 1440 * 100}%" title="${session.start} - ${session.end}${session.unlinked ? ' (unlinked — long-press to relink)' : ''}"><button class="schedule-handle start-handle edit-session-handle" data-contract-id="${contract.id}" data-session-id="${session.id}" data-handle="start" type="button" aria-label="Adjust ${contract.customerName} start time"></button><button class="schedule-handle end-handle edit-session-handle" data-contract-id="${contract.id}" data-session-id="${session.id}" data-handle="end" type="button" aria-label="Adjust ${contract.customerName} end time"></button></div>`; }).join('')}</div></div>`; }
function enableEditSessionHandle(handle, daySessions) { let resizing = false; let startX; let originalStart; let originalEnd; const sessions = state.editSessions[handle.dataset.contractId]; const session = sessions.find((item) => item.id === handle.dataset.sessionId); const chronoIndex = daySessions.findIndex((entry) => entry.session.id === session.id); const prevSession = session.unlinked ? undefined : nearestLinkedSession(daySessions, chronoIndex, -1); const nextSession = session.unlinked ? undefined : nearestLinkedSession(daySessions, chronoIndex, 1); handle.addEventListener('pointerdown', (event) => { event.preventDefault(); resizing = true; startX = event.clientX; originalStart = timeToMinutes(session.start); originalEnd = timeToMinutes(session.end); handle.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); updateDragTooltip(handle, session, event); }); handle.addEventListener('pointermove', (event) => { if (!resizing) return; const lane = handle.closest('.timeline-lane'); const delta = Math.round(((event.clientX - startX) / lane.getBoundingClientRect().width * 1440) / 5) * 5; if (handle.dataset.handle === 'start') { const floor = prevSession ? timeToMinutes(prevSession.start) : 0; session.start = minutesToTime(Math.min(originalEnd, Math.max(floor, originalStart + delta))); if (prevSession) prevSession.end = session.start; } else { const ceiling = nextSession ? timeToMinutes(nextSession.end) : 1440; session.end = minutesToTime(Math.max(originalStart, Math.min(ceiling, originalEnd + delta))); if (nextSession) nextSession.start = session.end; } const block = handle.closest('.scheduled-block'); block.style.left = `${timeToMinutes(session.start) / 1440 * 100}%`; block.style.width = `${Math.max(1, timeToMinutes(session.end) - timeToMinutes(session.start)) / 1440 * 100}%`; updateDragTooltip(handle, session, event); }); handle.addEventListener('pointerup', (event) => { if (!resizing) return; resizing = false; handle.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); hideDragTooltip(); enforceMinimumDuration(session, prevSession, nextSession, handle.dataset.handle); saveState(); renderEditTimes(); }); }
function enforceMinimumDuration(session, prevSession, nextSession, handleType) { const MIN = 5; if (handleType === 'start') { if (timeToMinutes(session.end) - timeToMinutes(session.start) <= 0) session.start = minutesToTime(timeToMinutes(session.end) - MIN); if (prevSession && timeToMinutes(prevSession.end) - timeToMinutes(prevSession.start) <= 0) { prevSession.end = minutesToTime(timeToMinutes(prevSession.start) + MIN); session.start = prevSession.end; } } else { if (timeToMinutes(session.end) - timeToMinutes(session.start) <= 0) session.end = minutesToTime(timeToMinutes(session.start) + MIN); if (nextSession && timeToMinutes(nextSession.end) - timeToMinutes(nextSession.start) <= 0) { nextSession.start = minutesToTime(timeToMinutes(nextSession.end) - MIN); session.end = nextSession.start; } } }
function renderContracts() {
  const filter = $('#filter-contracts').value;
  let contracts = state.order.map((id) => state.contracts.find((contract) => contract.id === id)).filter(Boolean);
  if (filter === 'visible') contracts = contracts.filter((contract) => !contract.hidden);
  if (filter === 'hidden') contracts = contracts.filter((contract) => contract.hidden);
  const emptyMessage = filter === 'hidden' ? 'No hidden contracts.' : 'No contracts on your dashboard yet. Add one to get started.';
  $('#contract-grid').innerHTML = contracts.length ? contracts.map(contractTemplate).join('') : `<div class="empty-dashboard">${emptyMessage}</div>`;
  document.querySelectorAll('.clock-button').forEach((button) => button.addEventListener('click', () => toggleClock(button.dataset.id)));
  document.querySelectorAll('.pin-action').forEach((button) => button.addEventListener('click', () => togglePin(button.dataset.id)));
  document.querySelectorAll('.edit-contract').forEach((button) => button.addEventListener('click', () => openContractModal(button.dataset.id)));
  document.querySelectorAll('.delete-contract').forEach((button) => button.addEventListener('click', () => toggleTileVisibility(button.dataset.id)));
  document.querySelectorAll('.tile').forEach(enableDrag);
  document.querySelectorAll('.tile-image img').forEach((img) => img.addEventListener('click', () => openImageViewer(img.getAttribute('src'))));
  updateMetrics();
}
function contractTemplate(contract) { const running = Boolean(contract.startedAt); return `<article class="tile ${contract.pinned ? 'is-pinned' : ''} ${contract.hidden ? 'is-hidden-contract' : ''}" draggable="${!contract.pinned}" data-id="${contract.id}"><div class="tile-title-bar"><span class="drag-handle" title="Drag to arrange">&#10303;</span><strong class="tile-customer-name" title="${contract.customerName}">${contract.customerName}</strong><button class="tile-action pin-action" data-id="${contract.id}" title="${contract.pinned ? 'Unpin tile' : 'Pin tile'}" aria-label="${contract.pinned ? 'Unpin tile' : 'Pin tile'}">&#128205;</button></div><div class="tile-meta"><span class="tile-code">${contract.number} | ${contract.suffix}${contract.suffixDescription ? ` | ${contract.suffixDescription}` : ''}</span>${contract.machineType ? `<span class="tile-machine-type">${contract.machineType}</span>` : ''}</div><div class="tile-image">${contract.image ? `<img src="${contract.image}" alt="${contract.customerName}">` : 'Image placeholder'}</div><div class="tile-times"><div class="time-block"><span>Accumulated</span><strong>${formatTime(contractSeconds(contract))}</strong></div><div class="time-block"><span>Current session</span><strong class="${running ? 'live-time' : ''}" data-live-id="${contract.id}">${running ? formatTime(Math.floor((Date.now() - contract.startedAt) / 1000)) : '00:00:00'}</strong></div></div><div class="tile-footer"><div class="tile-footer-left"><button class="tile-action edit-contract" data-id="${contract.id}" title="Edit tile" aria-label="Edit tile">&#9998;</button><button class="tile-action delete-contract" data-id="${contract.id}" title="${contract.hidden ? 'Restore tile to dashboard' : 'Remove tile from dashboard'}" aria-label="${contract.hidden ? 'Restore tile to dashboard' : 'Remove tile from dashboard'}">${contract.hidden ? '&#8635;' : '&times;'}</button></div><button class="clock-button ${running ? 'is-running' : ''}" data-id="${contract.id}" type="button">${running ? 'Stop clock' : 'Start clock'}</button></div></article>`; }
const imageViewerState = { scale: 1, fitScale: 1, x: 0, y: 0, naturalWidth: 0, naturalHeight: 0 };
function openImageViewer(src) { const img = $('#image-viewer-img'); const onReady = () => { imageViewerState.naturalWidth = img.naturalWidth; imageViewerState.naturalHeight = img.naturalHeight; zoomToFit(); }; img.onload = onReady; img.src = src; if (img.complete && img.naturalWidth) onReady(); $('#image-viewer-modal').classList.remove('is-hidden'); }
function closeImageViewer() { $('#image-viewer-modal').classList.add('is-hidden'); }
function applyImageTransform() { $('#image-viewer-img').style.transform = `translate(${imageViewerState.x}px, ${imageViewerState.y}px) scale(${imageViewerState.scale})`; }
function zoomToFit() { const viewport = $('#image-viewer-viewport'); const rect = viewport.getBoundingClientRect(); const fit = Math.min(rect.width / imageViewerState.naturalWidth, rect.height / imageViewerState.naturalHeight, 1) || 1; imageViewerState.fitScale = fit; imageViewerState.scale = fit; imageViewerState.x = 0; imageViewerState.y = 0; applyImageTransform(); }
function zoomBy(factor) { imageViewerState.scale = Math.min(4, Math.max(imageViewerState.fitScale, imageViewerState.scale * factor)); applyImageTransform(); }
function enableImagePan(img) { let panning = false; let startX; let startY; let originX; let originY; img.addEventListener('pointerdown', (event) => { panning = true; startX = event.clientX; startY = event.clientY; originX = imageViewerState.x; originY = imageViewerState.y; img.setPointerCapture(event.pointerId); }); img.addEventListener('pointermove', (event) => { if (!panning) return; imageViewerState.x = originX + (event.clientX - startX); imageViewerState.y = originY + (event.clientY - startY); applyImageTransform(); }); img.addEventListener('pointerup', (event) => { panning = false; img.releasePointerCapture(event.pointerId); }); }
function toggleClock(id) { const contract = state.contracts.find((item) => item.id === id); if (!contract) return; if (contract.startedAt) { contract.accumulated += Math.floor((Date.now() - contract.startedAt) / 1000); contract.startedAt = null; showToast(`${contract.customerName} stopped and saved`); } else { const runningContract = state.contracts.find((item) => item.id !== id && item.startedAt); if (runningContract) { runningContract.accumulated += Math.floor((Date.now() - runningContract.startedAt) / 1000); runningContract.startedAt = null; } contract.startedAt = Date.now(); showToast(runningContract ? `${runningContract.customerName} stopped; ${contract.customerName} is now running` : `${contract.customerName} is now running`); } saveState(); renderContracts(); }
function togglePin(id) { const contract = state.contracts.find((item) => item.id === id); contract.pinned = !contract.pinned; saveState(); renderContracts(); showToast(contract.pinned ? 'Tile pinned in place' : 'Tile can be rearranged'); }
function toggleTileVisibility(id) { const contract = state.contracts.find((item) => item.id === id); if (!contract) return; contract.hidden = !contract.hidden; saveState(); renderContracts(); showToast(contract.hidden ? 'Tile removed from dashboard' : 'Tile restored to dashboard'); }
function updateMetrics() { const total = state.contracts.reduce((sum, contract) => sum + contractSeconds(contract), 0); const active = state.contracts.filter((contract) => contract.startedAt).length; const nonWorking = state.users.reduce((sum, user) => sum + user.breaks.reduce((breakTotal, breakItem) => breakTotal + scheduleBreakSeconds(breakItem), 0), 0); const activeCount = $('#active-count'); $('#tracked-total').textContent = formatTime(total); if (activeCount) activeCount.textContent = active; $('#non-working-total').textContent = formatTime(nonWorking, false); }
function enableDrag(tile) { tile.addEventListener('dragstart', () => tile.classList.add('is-dragging')); tile.addEventListener('dragend', () => { tile.classList.remove('is-dragging'); const ids = [...document.querySelectorAll('.tile')].map((item) => item.dataset.id); state.order = ids.concat(state.order.filter((id) => !ids.includes(id))); saveState(); }); tile.addEventListener('dragover', (event) => { event.preventDefault(); if (tile.classList.contains('is-pinned')) return; const dragging = document.querySelector('.is-dragging'); if (dragging && dragging !== tile) { const box = tile.getBoundingClientRect(); tile.parentNode.insertBefore(dragging, event.clientY < box.top + box.height / 2 ? tile : tile.nextSibling); } }); }
function renderWorkingTimes() { const heading = $('#timeline-heading'); heading.innerHTML = Array.from({ length: 24 }, (_, hour) => `<span>${hour.toString().padStart(2, '0')}:00</span>`).join(''); const rows = $('#working-time-rows'); $('#empty-state').classList.toggle('is-hidden', state.users.length > 0); rows.innerHTML = state.users.map(userTemplate).join(''); rows.querySelectorAll('[data-user-field]').forEach((input) => input.addEventListener('change', () => { const user = state.users.find((item) => item.id === input.dataset.userId); user[input.dataset.userField] = input.value; saveState(); renderWorkingTimes(); updateMetrics(); })); rows.querySelectorAll('.remove-user').forEach((button) => button.addEventListener('click', () => removeUser(button.dataset.userId))); rows.querySelectorAll('.edit-break').forEach((button) => { button.addEventListener('click', () => { if (button.dataset.longPressed) { delete button.dataset.longPressed; return; } openScheduleModal(button.dataset.userId, button.dataset.breakId); }); enableBreakLongPress(button); }); rows.querySelectorAll('.add-break').forEach((button) => button.addEventListener('click', () => openScheduleModal(button.dataset.userId))); rows.querySelectorAll('.schedule-handle').forEach(enableScheduleHandle); }
function enableBreakLongPress(breakBlock) { let pressTimer; let longPressed = false; const cancelPress = () => { clearTimeout(pressTimer); }; breakBlock.addEventListener('pointerdown', (event) => { if (event.target.closest('.schedule-handle')) return; longPressed = false; pressTimer = setTimeout(() => { longPressed = true; showConfirm('Delete this break?').then((confirmed) => { if (confirmed) deleteBreak(breakBlock.dataset.userId, breakBlock.dataset.breakId); else breakBlock.dataset.longPressed = 'true'; }); }, 700); }); breakBlock.addEventListener('pointerup', () => { clearTimeout(pressTimer); if (longPressed) breakBlock.dataset.longPressed = 'true'; }); breakBlock.addEventListener('pointerleave', cancelPress); breakBlock.addEventListener('pointercancel', cancelPress); }
function deleteBreak(userId, breakId) { const user = state.users.find((item) => item.id === userId); if (!user) return; user.breaks = user.breaks.filter((breakItem) => breakItem.id !== breakId); saveState(); renderWorkingTimes(); updateMetrics(); showToast('Break deleted'); }
function updateDragTooltip(handle, target, event) { const tooltip = $('#drag-tooltip'); tooltip.textContent = `${handle.dataset.handle === 'start' ? 'Start' : 'End'}: ${target[handle.dataset.handle]}`; tooltip.style.left = `${event.clientX + 12}px`; tooltip.style.top = `${event.clientY - 38}px`; tooltip.classList.remove('is-hidden'); }
function hideDragTooltip() { $('#drag-tooltip').classList.add('is-hidden'); }
function enableScheduleHandle(handle) { let resizing = false; let startX; let originalStart; let originalEnd; const user = state.users.find((item) => item.id === handle.dataset.userId); const breakItem = user?.breaks.find((item) => item.id === handle.dataset.breakId); const target = breakItem || user; handle.title = `Drag to adjust ${handle.dataset.handle} time`; handle.addEventListener('pointerdown', (event) => { event.preventDefault(); event.stopPropagation(); resizing = true; startX = event.clientX; originalStart = timeToMinutes(target.start); originalEnd = timeToMinutes(target.end); handle.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); updateDragTooltip(handle, target, event); }); handle.addEventListener('pointermove', (event) => { if (!resizing) return; const lane = handle.closest('.timeline-lane'); const delta = Math.round(((event.clientX - startX) / lane.getBoundingClientRect().width * 1440) / 5) * 5; if (handle.dataset.handle === 'start') target.start = minutesToTime(Math.min(originalEnd - 5, Math.max(0, originalStart + delta))); else target.end = minutesToTime(Math.max(originalStart + 5, Math.min(1440, originalEnd + delta))); const block = handle.closest(breakItem ? '.break-block' : '.scheduled-block'); const start = timeToMinutes(target.start); const end = timeToMinutes(target.end); block.style.left = `${start / 1440 * 100}%`; block.style.width = `${Math.max(0, end - start) / 1440 * 100}%`; if (!breakItem) { const row = handle.closest('.schedule-row'); row.querySelector(`[data-user-field="start"]`).value = target.start; row.querySelector(`[data-user-field="end"]`).value = target.end; } updateDragTooltip(handle, target, event); }); handle.addEventListener('pointerup', (event) => { if (!resizing) return; resizing = false; handle.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); hideDragTooltip(); saveState(); renderWorkingTimes(); updateMetrics(); }); handle.addEventListener('pointercancel', () => { if (!resizing) return; resizing = false; document.body.classList.remove('is-resizing'); hideDragTooltip(); }); }
function userTemplate(user) { const start = timeToMinutes(user.start); const end = timeToMinutes(user.end); const workWidth = Math.max(0, end - start) / 1440 * 100; return `<div class="schedule-row"><div class="user-cell"><div class="user-name-line"><input type="text" class="user-name-input" data-user-id="${user.id}" data-user-field="name" value="${user.name}" aria-label="Edit name"><button class="remove-user" data-user-id="${user.id}" type="button" title="Remove ${user.name}" aria-label="Remove ${user.name}">&times;</button></div><span><input type="time" data-user-id="${user.id}" data-user-field="start" value="${user.start}"> - <input type="time" data-user-id="${user.id}" data-user-field="end" value="${user.end}"></span><button class="add-break" data-user-id="${user.id}" type="button" title="Add a break for ${user.name}">+ break</button></div><div class="timeline-lane"><div class="scheduled-block" style="left:${start / 1440 * 100}%;width:${workWidth}%"><button class="schedule-handle start-handle" data-user-id="${user.id}" data-handle="start" type="button" title="Drag to adjust start time" aria-label="Adjust ${user.name} start time"></button><button class="schedule-handle end-handle" data-user-id="${user.id}" data-handle="end" type="button" title="Drag to adjust end time" aria-label="Adjust ${user.name} end time"></button></div>${user.breaks.map((breakItem) => `<div class="break-block edit-break" data-user-id="${user.id}" data-break-id="${breakItem.id}" style="left:${timeToMinutes(breakItem.start) / 1440 * 100}%;width:${Math.max(1, timeToMinutes(breakItem.end) - timeToMinutes(breakItem.start)) / 1440 * 100}%" title="Edit ${breakItem.type}: ${breakItem.start} - ${breakItem.end}"><button class="schedule-handle start-handle break-handle" data-user-id="${user.id}" data-break-id="${breakItem.id}" data-handle="start" type="button" title="Drag to adjust break start time" aria-label="Adjust ${breakItem.type} start time"></button><button class="schedule-handle end-handle break-handle" data-user-id="${user.id}" data-break-id="${breakItem.id}" data-handle="end" type="button" title="Drag to adjust break end time" aria-label="Adjust ${breakItem.type} end time"></button></div>`).join('')}</div></div>`; }
function overtimeLabel(user) { const start = timeToMinutes(user.start); const end = timeToMinutes(user.end); return start === end ? 'No scheduled hours' : `Overtime before ${user.start} / after ${user.end}`; }
function removeUser(id) { if (id === 'jordan') { showToast('Jordan Reed is the signed-in user'); return; } state.users = state.users.filter((user) => user.id !== id); saveState(); renderWorkingTimes(); updateMetrics(); showToast('User removed'); }
let editingScheduleUserId = null;
let editingScheduleBreakId = null;
let editingContractId = null;
function openContractModal(contractId = null) { editingContractId = contractId; const contract = contractId ? state.contracts.find((item) => item.id === contractId) : null; $('#contract-modal-title').textContent = contract ? 'Edit tile' : 'Add tile'; $('#contract-submit').innerHTML = contract ? 'Save changes' : '<span>+</span> Add tile'; $('#contract-customer-name').value = contract?.customerName || ''; $('#contract-number').value = contract?.number || ''; $('#contract-suffix').value = contract?.suffix || ''; $('#contract-suffix-description').value = contract?.suffixDescription || ''; populateMachineTypeOptions(); $('#contract-machine-type').value = contract?.machineType || ''; $('#contract-image').value = ''; $('#contract-image-preview').innerHTML = contract?.image ? `<img src="${contract.image}" alt="Current image"><span>Current image — choose a file to replace it</span>` : ''; $('#contract-modal').classList.remove('is-hidden'); $('#contract-customer-name').focus(); }
function openScheduleModal(userId = null, breakId = null) { editingScheduleUserId = userId; editingScheduleBreakId = breakId; const user = state.users.find((item) => item.id === userId); const breakItem = user?.breaks.find((item) => item.id === breakId); $('#schedule-modal-title').textContent = user ? `Edit ${user.name}` : 'Add user'; $('#schedule-user-name').value = user?.name || ''; $('#schedule-start').value = user?.start || '06:00'; $('#schedule-end').value = user?.end || '15:00'; $('#schedule-break-start').value = breakItem?.start || '12:30'; $('#schedule-break-end').value = breakItem?.end || '13:05'; $('#schedule-modal').classList.remove('is-hidden'); $('#schedule-user-name').focus(); }
function closeScheduleModal() { $('#schedule-modal').classList.add('is-hidden'); $('#schedule-form').reset(); editingScheduleUserId = null; editingScheduleBreakId = null; }
function saveSchedule(event) { event.preventDefault(); const formData = new FormData(event.currentTarget); const name = formData.get('name').trim(); const start = formData.get('start'); const end = formData.get('end'); const breakStart = formData.get('breakStart'); const breakEnd = formData.get('breakEnd'); if (timeToMinutes(end) <= timeToMinutes(start) || timeToMinutes(breakEnd) <= timeToMinutes(breakStart)) { showToast('End times must be after start times'); return; } const user = editingScheduleUserId ? state.users.find((item) => item.id === editingScheduleUserId) : { id: `user-${Date.now()}`, name: '', start: '', end: '', breaks: [] }; user.name = name; user.start = start; user.end = end; if (editingScheduleBreakId) { const breakItem = user.breaks.find((item) => item.id === editingScheduleBreakId); breakItem.start = breakStart; breakItem.end = breakEnd; } else { user.breaks.push({ id: `break-${Date.now()}`, type: 'Break', start: breakStart, end: breakEnd }); } if (!editingScheduleUserId) state.users.push(user); saveState(); renderWorkingTimes(); updateMetrics(); closeScheduleModal(); showToast(editingScheduleUserId ? 'Working times updated' : 'User added to working times'); }
function closeContractModal() { $('#contract-modal').classList.add('is-hidden'); $('#contract-form').reset(); $('#contract-image-preview').innerHTML = ''; editingContractId = null; }
function saveContract(event) { event.preventDefault(); const formData = new FormData(event.currentTarget); const customerName = formData.get('customerName').trim().toUpperCase(); const number = formData.get('number').trim().toUpperCase(); const suffix = formData.get('suffix').trim().toUpperCase(); const suffixDescription = formData.get('suffixDescription').trim().toUpperCase(); const machineType = formData.get('machineType'); const imageFile = formData.get('image'); const contractId = editingContractId; const finishSaveContract = (image) => { if (contractId) { const contract = state.contracts.find((item) => item.id === contractId); contract.customerName = customerName; contract.number = number; contract.suffix = suffix; contract.suffixDescription = suffixDescription; contract.machineType = machineType; if (image) contract.image = image; } else { const id = `contract-${Date.now()}`; state.contracts.push({ id, customerName, number, suffix, suffixDescription, machineType, image, accumulated: 0, startedAt: null, pinned: false, hidden: false }); state.order.push(id); state.editSessions[id] = [{ id: `session-${id}-1`, date: EDIT_TIMES_DATE, start: '09:00', end: '09:30' }]; } const saved = saveState(); renderContracts(); renderEditTimes(); closeContractModal(); showToast(saved ? (contractId ? 'Tile updated' : 'Tile added to dashboard') : 'Changes made, but could not be saved (storage limit reached — try a smaller image)'); }; if (imageFile && imageFile.size) { const reader = new FileReader(); reader.onload = () => finishSaveContract(reader.result); reader.readAsDataURL(imageFile); } else { finishSaveContract(null); } }
function populateMachineTypeOptions() { const select = $('#contract-machine-type'); const current = select.value; select.innerHTML = '<option value="">Select machine type</option>' + state.machineTypes.map((type) => `<option value="${type}">${type}</option>`).join(''); select.value = current; }
function openListsModal() { $('#lists-modal').classList.remove('is-hidden'); renderMachineTypeList(); }
function closeListsModal() { $('#lists-modal').classList.add('is-hidden'); $('#machine-type-input').value = ''; }
function renderMachineTypeList() { const list = $('#machine-type-list'); list.innerHTML = state.machineTypes.length ? state.machineTypes.map((type) => `<li>${type}<button class="remove-list-item" data-type="${type}" type="button" aria-label="Remove ${type}">&times;</button></li>`).join('') : '<li class="list-empty">No machine types yet.</li>'; list.querySelectorAll('.remove-list-item').forEach((button) => button.addEventListener('click', () => removeMachineType(button.dataset.type))); populateMachineTypeOptions(); }
function addMachineType(event) { event.preventDefault(); const input = $('#machine-type-input'); const value = input.value.trim(); if (!value || state.machineTypes.includes(value)) { input.value = ''; return; } state.machineTypes.push(value); input.value = ''; saveState(); renderMachineTypeList(); }
function removeMachineType(type) { state.machineTypes = state.machineTypes.filter((item) => item !== type); saveState(); renderMachineTypeList(); }
let confirmResolve = null;
function showConfirm(message, confirmLabel = 'Confirm') { return new Promise((resolve) => { confirmResolve = resolve; $('#confirm-modal-message').textContent = message; $('#confirm-modal-confirm').textContent = confirmLabel; $('#confirm-modal').classList.remove('is-hidden'); }); }
function closeConfirmModal(result) { $('#confirm-modal').classList.add('is-hidden'); if (confirmResolve) { confirmResolve(result); confirmResolve = null; } }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('is-visible'), 2300); }
function commitTimes() { showToast(`Times committed for ${$('#edit-times-date').value}`); }
function commitContract(contract) { if (!contract?.startedAt) return; contract.accumulated += Math.floor((Date.now() - contract.startedAt) / 1000); contract.startedAt = null; }
function handleBreakState() { const breakItem = currentBreak(); if (breakItem && !state.breakState) { const runningContract = state.contracts.find((contract) => contract.startedAt); if (runningContract) { commitContract(runningContract); state.breakState = { contractId: runningContract.id }; saveState(); showToast(`${runningContract.customerName} paused for break`); } } else if (!breakItem && state.breakState) { const pausedContract = state.contracts.find((contract) => contract.id === state.breakState.contractId); if (pausedContract && !state.contracts.some((contract) => contract.startedAt)) { pausedContract.startedAt = Date.now(); showToast(`${pausedContract.customerName} resumed after break`); } state.breakState = null; saveState(); } }
function tick() { handleBreakState(); state.contracts.filter((contract) => contract.startedAt).forEach((contract) => { const live = document.querySelector(`[data-live-id="${contract.id}"]`); if (live) live.textContent = formatTime(Math.floor((Date.now() - contract.startedAt) / 1000)); }); updateMetrics(); }
document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('is-active', item === button)); document.querySelectorAll('[data-view-panel]').forEach((panel) => panel.classList.toggle('is-hidden', panel.dataset.viewPanel !== button.dataset.view)); }));
$('#add-contract').addEventListener('click', () => openContractModal()); $('#contract-form').addEventListener('submit', saveContract); $('#close-contract-modal').addEventListener('click', closeContractModal); $('#cancel-contract').addEventListener('click', closeContractModal); $('#contract-modal').addEventListener('click', (event) => { if (event.target.id === 'contract-modal') closeContractModal(); }); $('#add-user').addEventListener('click', () => openScheduleModal()); $('#schedule-form').addEventListener('submit', saveSchedule); $('#close-schedule-modal').addEventListener('click', closeScheduleModal); $('#cancel-schedule').addEventListener('click', closeScheduleModal); $('#schedule-modal').addEventListener('click', (event) => { if (event.target.id === 'schedule-modal') closeScheduleModal(); }); $('#edit-times-date').addEventListener('change', renderEditTimes); $('#filter-contracts').addEventListener('change', renderContracts); $('#commit-times').addEventListener('click', commitTimes);
$('#open-lists').addEventListener('click', openListsModal); $('#lists-form').addEventListener('submit', addMachineType); $('#close-lists-modal').addEventListener('click', closeListsModal); $('#close-lists').addEventListener('click', closeListsModal); $('#lists-modal').addEventListener('click', (event) => { if (event.target.id === 'lists-modal') closeListsModal(); });
$('#confirm-modal-cancel').addEventListener('click', () => closeConfirmModal(false)); $('#confirm-modal-confirm').addEventListener('click', () => closeConfirmModal(true)); $('#confirm-modal').addEventListener('click', (event) => { if (event.target.id === 'confirm-modal') closeConfirmModal(false); });
$('#close-image-viewer').addEventListener('click', closeImageViewer); $('#image-viewer-modal').addEventListener('click', (event) => { if (event.target.id === 'image-viewer-modal') closeImageViewer(); }); $('#image-zoom-in').addEventListener('click', () => zoomBy(1.25)); $('#image-zoom-out').addEventListener('click', () => zoomBy(1 / 1.25)); $('#image-zoom-fit').addEventListener('click', zoomToFit); $('#image-viewer-viewport').addEventListener('wheel', (event) => { event.preventDefault(); zoomBy(event.deltaY < 0 ? 1.15 : 1 / 1.15); }, { passive: false });
enableImagePan($('#image-viewer-img'));
const sidebarResize = $('.sidebar-resize'); let resizeStartX; let resizeStartWidth;
sidebarResize.addEventListener('pointerdown', (event) => { resizeStartX = event.clientX; resizeStartWidth = $('.sidebar').getBoundingClientRect().width; sidebarResize.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); });
sidebarResize.addEventListener('pointermove', (event) => { if (!sidebarResize.hasPointerCapture(event.pointerId)) return; const width = Math.min(360, Math.max(190, resizeStartWidth + event.clientX - resizeStartX)); document.documentElement.style.setProperty('--sidebar-width', `${width}px`); localStorage.setItem(SIDEBAR_WIDTH_KEY, width); });
sidebarResize.addEventListener('pointerup', (event) => { sidebarResize.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); });
renderContracts(); renderWorkingTimes(); renderEditTimes(); setInterval(tick, 1000);
