const STORAGE_KEY = 'contract-time-tracker-v2';
const SIDEBAR_WIDTH_KEY = 'contract-time-sidebar-width';
const defaultState = {
  contracts: [
    { id: 'meridian', customerName: 'Meridian House', number: 'CNT-1048', suffix: 'A-01', suffixDescription: '', machineType: '', image: null, startedAt: null, pinned: false, hidden: false },
    { id: 'northline', customerName: 'Northline Depot', number: 'CNT-0917', suffix: 'B-04', suffixDescription: '', machineType: '', image: null, startedAt: null, pinned: true, hidden: false },
    { id: 'harbour', customerName: 'Harbour Exchange', number: 'CNT-1182', suffix: 'C-02', suffixDescription: '', machineType: '', image: null, startedAt: null, pinned: false, hidden: false },
    { id: 'civic', customerName: 'Civic Centre Refurb', number: 'CNT-0974', suffix: 'A-03', suffixDescription: '', machineType: '', image: null, startedAt: null, pinned: false, hidden: false }
  ],
  nonWorking: [
    { id: 'nw-1', date: '2026-09-12', category: 'Break', start: '12:00', end: '12:30' },
    { id: 'nw-2', date: '2026-09-11', category: 'Annual leave', start: '09:00', end: '17:00' }
  ],
  machineTypes: ['Excavator', 'Dumper truck', 'Roller', 'Crane'],
  suffixDescriptions: [],
  customers: [],
  costCentres: [],
  defaultWorkingTimes: { start: '07:00', end: '16:00', breaks: [{ start: '09:00', end: '09:15' }, { start: '12:30', end: '13:05' }] },
  contractInfo: [],
  committedDates: [],
  adminMode: false,
  order: ['meridian', 'northline', 'harbour', 'civic'],
  users: [{ id: 'jordan', name: 'Jordan Reed', email: '', userType: 'admin' }],
  workingTimes: [{ id: 'wt-jordan', userId: 'jordan', start: '09:00', end: '17:00', breaks: [{ id: 'break-jordan', type: 'Break', start: '12:00', end: '12:30' }] }],
  breakState: null
};

let state = loadState();
let toastTimer;
const $ = (selector) => document.querySelector(selector);
function localDateString(timestamp) { const d = new Date(timestamp); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
function timeOfDayString(timestamp) { const d = new Date(timestamp); return `${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}`; }
function timeOfDaySecondsString(timestamp) { const d = new Date(timestamp); return `${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}:${d.getSeconds().toString().padStart(2, '0')}`; }
const TODAY = localDateString(Date.now());
state.users = state.users || structuredClone(defaultState.users);
state.users.forEach((user) => { user.email = user.email ?? ''; user.userType = user.userType ?? 'user'; user.costCentre = user.costCentre ?? ''; });
const needsWorkingTimesMigration = state.users.some((user) => user.start !== undefined || user.end !== undefined || user.breaks !== undefined);
state.workingTimes = (state.workingTimes && state.workingTimes.length) ? state.workingTimes : structuredClone(defaultState.workingTimes);
if (needsWorkingTimesMigration) { state.users.forEach((user) => { if ((user.start || user.end || (user.breaks && user.breaks.length)) && !state.workingTimes.some((wt) => wt.userId === user.id)) { state.workingTimes.push({ id: `wt-${user.id}`, userId: user.id, start: user.start || '06:00', end: user.end || '15:00', breaks: user.breaks || [] }); } }); }
state.users.forEach((user) => { delete user.start; delete user.end; delete user.breaks; });
state.machineTypes = state.machineTypes || structuredClone(defaultState.machineTypes);
state.suffixDescriptions = state.suffixDescriptions || structuredClone(defaultState.suffixDescriptions);
state.customers = state.customers || structuredClone(defaultState.customers);
state.costCentres = state.costCentres || structuredClone(defaultState.costCentres);
state.defaultWorkingTimes = state.defaultWorkingTimes || structuredClone(defaultState.defaultWorkingTimes);
if (!state.defaultWorkingTimes.breaks || state.defaultWorkingTimes.breaks.length < 2) state.defaultWorkingTimes.breaks = structuredClone(defaultState.defaultWorkingTimes.breaks);
state.contractInfo = state.contractInfo || structuredClone(defaultState.contractInfo);
state.committedDates = state.committedDates || structuredClone(defaultState.committedDates);
state.adminMode = state.adminMode ?? defaultState.adminMode;
state.contractInfo.forEach((record) => { record.orderConfirmationLink = record.orderConfirmationLink ?? ''; record.expanded = record.expanded ?? false; if (!record.suffixes) { record.suffixes = (record.contractLetter || record.orderConfirmationDescription) ? [{ id: `suffix-${record.id}`, letter: record.contractLetter ?? '', description: record.orderConfirmationDescription ?? '' }] : []; } delete record.contractLetter; delete record.orderConfirmationDescription; if (record.machineType === undefined) record.machineType = record.description ?? ''; delete record.description; record.suffixes.forEach((suffix) => { suffix.letter = (suffix.letter || '').toUpperCase(); }); });
state.contracts.forEach((contract) => { if (contract.customerName === undefined) contract.customerName = contract.description ?? contract.name ?? ''; delete contract.description; delete contract.name; delete contract.accumulated; });
state.contracts.forEach((contract) => { if (contract.customerName && !state.customers.includes(contract.customerName)) state.customers.push(contract.customerName); });
state.contracts.forEach((contract) => { if (contract.number && !state.contractInfo.some((record) => record.number === contract.number)) { state.contractInfo.push({ id: `info-${contract.id}`, number: contract.number, machineType: contract.machineType || '', customerName: contract.customerName || '', oneDriveLink: '', orderConfirmationLink: '', expanded: false, suffixes: contract.suffix ? [{ id: `suffix-${contract.id}`, letter: contract.suffix, description: contract.suffixDescription || '' }] : [] }); } });
state.breakState = state.breakState || null;
state.editSessions = state.editSessions || {};
const EDIT_TIMES_DATE = TODAY;
if (!Object.keys(state.editSessions).length) {
  const rotation = state.contracts.map((contract) => contract.id);
  for (let minutes = 360, i = 0; minutes < 900; minutes += 60, i += 1) {
    const contractId = rotation[i % rotation.length];
    const sessions = state.editSessions[contractId] || (state.editSessions[contractId] = []);
    sessions.push({ id: `session-${contractId}-${sessions.length + 1}`, date: EDIT_TIMES_DATE, start: minutesToTime(minutes), end: minutesToTime(minutes + 60) });
  }
}
$('#today-date').textContent = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
$('#edit-times-date').value = TODAY;
const savedSidebarWidth = Number(localStorage.getItem(SIDEBAR_WIDTH_KEY));
if (savedSidebarWidth >= 190 && savedSidebarWidth <= 360) document.documentElement.style.setProperty('--sidebar-width', `${savedSidebarWidth}px`);
const formatTime = (seconds, includeHours = true) => {
  const safeSeconds = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(safeSeconds / 3600).toString().padStart(2, '0');
  const minutes = Math.floor((safeSeconds % 3600) / 60).toString().padStart(2, '0');
  const remainder = (safeSeconds % 60).toString().padStart(2, '0');
  return includeHours ? `${hours}:${minutes}:${remainder}` : `${hours}:${minutes}`;
};
function loadState() { try { return { ...defaultState, ...JSON.parse(localStorage.getItem(STORAGE_KEY)) }; } catch { return structuredClone(defaultState); } }
function saveState() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); return true; } catch (error) { return false; } }
function sessionSecondsFor(contractId, filterFn) { const sessions = state.editSessions[contractId] || []; return sessions.filter(filterFn).reduce((sum, session) => sum + Math.max(0, (timeToMinutes(session.end) - timeToMinutes(session.start)) * 60), 0); }
function todaySessionSeconds(contractId) { return sessionSecondsFor(contractId, (session) => session.date === TODAY); }
function lifetimeSessionSeconds(contractId) { return sessionSecondsFor(contractId, () => true); }
function contractSeconds(contract) { return lifetimeSessionSeconds(contract.id) + (contract.startedAt ? Math.floor((Date.now() - contract.startedAt) / 1000) : 0); }
function isDateCommitted(date) { return state.committedDates.includes(date); }
function recordSession(contract, startMs, endMs) { const safeEndMs = Math.max(endMs, startMs + 1000); const date = localDateString(startMs); const start = timeOfDaySecondsString(startMs); const end = timeOfDaySecondsString(safeEndMs); const sessions = state.editSessions[contract.id] || (state.editSessions[contract.id] = []); sessions.push({ id: `session-${contract.id}-${Date.now()}`, date, start, end }); }
function nonWorkingSeconds(entry) { const [startHour, startMinute] = entry.start.split(':').map(Number); const [endHour, endMinute] = entry.end.split(':').map(Number); return Math.max(0, (endHour * 60 + endMinute - startHour * 60 - startMinute) * 60); }
function timeToMinutes(value) { const [hours, minutes, seconds] = value.split(':').map(Number); return hours * 60 + minutes + (seconds || 0) / 60; }
function minutesToTime(minutes) { const rounded = Math.round(minutes); return `${Math.floor(rounded / 60).toString().padStart(2, '0')}:${(rounded % 60).toString().padStart(2, '0')}`; }
function scheduleBreakSeconds(breakItem) { return Math.max(0, (timeToMinutes(breakItem.end) - timeToMinutes(breakItem.start)) * 60); }
function currentBreak() { const entry = state.workingTimes.find((item) => item.userId === 'jordan'); if (!entry) return null; const now = new Date(); const minutes = now.getHours() * 60 + now.getMinutes(); return entry.breaks.find((breakItem) => minutes >= timeToMinutes(breakItem.start) && minutes < timeToMinutes(breakItem.end)); }
function sessionsForDate(date) { const list = []; state.contracts.forEach((contract) => { (state.editSessions[contract.id] || []).forEach((session) => { if (session.date === date) list.push({ contractId: contract.id, session }); }); }); list.sort((a, b) => timeToMinutes(a.session.start) - timeToMinutes(b.session.start)); return list; }
// EXPERIMENTAL — session unlink/relink via long-press on an Edit Times bar. To remove this feature: delete
// nearestLinkedSession, enableSessionLongPress, toggleSessionLink; the "session.unlinked ? ..." conditions in
// enableEditSessionHandle and editContractTemplate's block markup; the enableSessionLongPress wiring in
// renderEditTimes; and the .is-unlinked rule in styles.css.
function nearestLinkedSession(daySessions, index, step) { for (let i = index + step; i >= 0 && i < daySessions.length; i += step) { if (!daySessions[i].session.unlinked) return daySessions[i].session; } return undefined; }
function toggleSessionLink(contractId, sessionId) { const sessions = state.editSessions[contractId]; const session = sessions?.find((item) => item.id === sessionId); if (!session) return; if (session.unlinked) { const daySessions = sessionsForDate(session.date); const idx = daySessions.findIndex((entry) => entry.session.id === sessionId); const prev = daySessions[idx - 1]?.session; const next = daySessions[idx + 1]?.session; if (prev) session.start = prev.end; if (next) session.end = next.start; session.unlinked = false; showToast('Session linked to nearest times'); } else { session.unlinked = true; showToast('Session unlinked — drag it without affecting neighbours'); } saveState(); renderEditTimes(); }
function removeSession(contractId, sessionId) { const sessions = state.editSessions[contractId]; if (!sessions) return; showConfirm('Remove this time block?').then((confirmed) => { if (!confirmed) return; state.editSessions[contractId] = sessions.filter((item) => item.id !== sessionId); saveState(); renderEditTimes(); showToast('Time block removed'); }); }
function enableSessionLongPress(block) { let pressTimer; const cancelPress = () => clearTimeout(pressTimer); block.addEventListener('pointerdown', (event) => { if (event.target.closest('.schedule-handle')) return; pressTimer = setTimeout(() => toggleSessionLink(block.dataset.contractId, block.dataset.sessionId), 700); }); block.addEventListener('pointerup', cancelPress); block.addEventListener('pointerleave', cancelPress); block.addEventListener('pointercancel', cancelPress); }
function renderEditTimes() { const heading = $('#edit-timeline-heading'); if (!heading) return; heading.innerHTML = Array.from({ length: 24 }, (_, hour) => `<span>${hour.toString().padStart(2, '0')}:00</span>`).join(''); const date = $('#edit-times-date').value; updateCommittedUi(); const rows = $('#edit-time-rows'); const daySessions = sessionsForDate(date); const firstStart = {}; daySessions.forEach(({ contractId, session }) => { if (!(contractId in firstStart)) firstStart[contractId] = timeToMinutes(session.start); }); const sortedContracts = state.contracts.slice().sort((a, b) => (firstStart[a.id] ?? Infinity) - (firstStart[b.id] ?? Infinity)); rows.innerHTML = sortedContracts.map((contract) => editContractTemplate(contract, date)).join('') + editBreakBandsTemplate(); rows.querySelectorAll('.edit-session-handle').forEach((handle) => enableEditSessionHandle(handle, daySessions)); rows.querySelectorAll('.edit-session-block').forEach((block) => { enableSessionLongPress(block); block.addEventListener('dblclick', (event) => { if (event.target.closest('.schedule-handle')) return; removeSession(block.dataset.contractId, block.dataset.sessionId); }); }); }
function editBreakBandsTemplate() { const entry = state.workingTimes.find((item) => item.userId === 'jordan'); if (!entry || !entry.breaks.length) return ''; return `<div class="edit-break-overlay">${entry.breaks.map((breakItem) => { const start = timeToMinutes(breakItem.start); const end = timeToMinutes(breakItem.end); return `<div class="edit-break-band" style="left:${start / 1440 * 100}%;width:${Math.max(1, end - start) / 1440 * 100}%" title="${breakItem.type}: ${breakItem.start} - ${breakItem.end}"></div>`; }).join('')}</div>`; }
function editContractTemplate(contract, date) { const sessions = (state.editSessions[contract.id] || []).filter((session) => session.date === date); return `<div class="schedule-row edit-session-row"><div class="user-cell edit-contract-cell"><div class="edit-contract-top"><strong>${contract.customerName}</strong><span class="edit-contract-code">${contract.number}</span></div><span class="edit-contract-code">${contract.suffix}${contract.suffixDescription ? ` | ${contract.suffixDescription}` : ''}</span></div><div class="timeline-lane">${sessions.map((session) => { const start = timeToMinutes(session.start); const end = timeToMinutes(session.end); return `<div class="scheduled-block edit-session-block ${session.unlinked ? 'is-unlinked' : ''}" data-contract-id="${contract.id}" data-session-id="${session.id}" style="left:${start / 1440 * 100}%;width:${Math.max(1, end - start) / 1440 * 100}%" title="${session.start} - ${session.end}${session.unlinked ? ' (unlinked — long-press to relink)' : ''}"><button class="schedule-handle start-handle edit-session-handle" data-contract-id="${contract.id}" data-session-id="${session.id}" data-handle="start" type="button" aria-label="Adjust ${contract.customerName} start time"></button><button class="schedule-handle end-handle edit-session-handle" data-contract-id="${contract.id}" data-session-id="${session.id}" data-handle="end" type="button" aria-label="Adjust ${contract.customerName} end time"></button></div>`; }).join('')}</div></div>`; }
function enableEditSessionHandle(handle, daySessions) { let resizing = false; let startX; let originalStart; let originalEnd; const sessions = state.editSessions[handle.dataset.contractId]; const session = sessions.find((item) => item.id === handle.dataset.sessionId); const chronoIndex = daySessions.findIndex((entry) => entry.session.id === session.id); const prevSession = session.unlinked ? undefined : nearestLinkedSession(daySessions, chronoIndex, -1); const nextSession = session.unlinked ? undefined : nearestLinkedSession(daySessions, chronoIndex, 1); handle.addEventListener('pointerdown', (event) => { event.preventDefault(); resizing = true; startX = event.clientX; originalStart = timeToMinutes(session.start); originalEnd = timeToMinutes(session.end); handle.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); updateDragTooltip(handle, session, event); }); handle.addEventListener('pointermove', (event) => { if (!resizing) return; const lane = handle.closest('.timeline-lane'); const delta = Math.round(((event.clientX - startX) / lane.getBoundingClientRect().width * 1440) / 5) * 5; if (handle.dataset.handle === 'start') { const floor = prevSession ? timeToMinutes(prevSession.start) : 0; session.start = minutesToTime(Math.min(originalEnd, Math.max(floor, originalStart + delta))); if (prevSession) prevSession.end = session.start; } else { const ceiling = nextSession ? timeToMinutes(nextSession.end) : 1440; session.end = minutesToTime(Math.max(originalStart, Math.min(ceiling, originalEnd + delta))); if (nextSession) nextSession.start = session.end; } const block = handle.closest('.scheduled-block'); block.style.left = `${timeToMinutes(session.start) / 1440 * 100}%`; block.style.width = `${Math.max(1, timeToMinutes(session.end) - timeToMinutes(session.start)) / 1440 * 100}%`; updateDragTooltip(handle, session, event); }); handle.addEventListener('pointerup', (event) => { if (!resizing) return; resizing = false; handle.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); hideDragTooltip(); enforceMinimumDuration(session, prevSession, nextSession, handle.dataset.handle); saveState(); renderEditTimes(); }); }
function enforceMinimumDuration(session, prevSession, nextSession, handleType) { const MIN = 5; if (handleType === 'start') { if (timeToMinutes(session.end) - timeToMinutes(session.start) <= 0) session.start = minutesToTime(timeToMinutes(session.end) - MIN); if (prevSession && timeToMinutes(prevSession.end) - timeToMinutes(prevSession.start) <= 0) { prevSession.end = minutesToTime(timeToMinutes(prevSession.start) + MIN); session.start = prevSession.end; } } else { if (timeToMinutes(session.end) - timeToMinutes(session.start) <= 0) session.end = minutesToTime(timeToMinutes(session.start) + MIN); if (nextSession && timeToMinutes(nextSession.end) - timeToMinutes(nextSession.start) <= 0) { nextSession.start = minutesToTime(timeToMinutes(nextSession.end) - MIN); session.end = nextSession.start; } } }
function renderContracts() {
  const filter = $('#filter-contracts').value;
  let contracts = state.order.map((id) => state.contracts.find((contract) => contract.id === id)).filter(Boolean);
  if (filter === 'visible') contracts = contracts.filter((contract) => !contract.hidden);
  if (filter === 'hidden') contracts = contracts.filter((contract) => contract.hidden);
  const emptyMessage = filter === 'hidden' ? 'No hidden contracts.' : 'No contracts on your dashboard yet. Add one to get started.';
  $('#contract-grid').innerHTML = contracts.length ? contracts.map(contractTemplate).join('') : `<div class="empty-dashboard">${emptyMessage}</div>`;
  document.querySelectorAll('.clock-button').forEach((button) => button.addEventListener('click', () => toggleClock(button.dataset.id)));
  document.querySelectorAll('.pin-action').forEach((button) => button.addEventListener('click', () => togglePin(button.dataset.id)));
  document.querySelectorAll('.edit-contract').forEach((button) => button.addEventListener('click', () => openContractModal(button.dataset.id)));
  document.querySelectorAll('.delete-contract').forEach((button) => button.addEventListener('click', () => toggleTileVisibility(button.dataset.id)));
  document.querySelectorAll('.tile').forEach(enableDrag);
  document.querySelectorAll('.tile-image img').forEach((img) => img.addEventListener('click', () => openImageViewer(img.getAttribute('src'))));
  updateMetrics();
}
function contractTemplate(contract) { const running = Boolean(contract.startedAt); return `<article class="tile ${contract.pinned ? 'is-pinned' : ''} ${contract.hidden ? 'is-hidden-contract' : ''}" draggable="${!contract.pinned}" data-id="${contract.id}"><div class="tile-title-bar"><span class="drag-handle" title="Drag to arrange">&#10303;</span><strong class="tile-customer-name" title="${contract.customerName}">${contract.customerName}</strong><button class="tile-action pin-action" data-id="${contract.id}" title="${contract.pinned ? 'Unpin tile' : 'Pin tile'}" aria-label="${contract.pinned ? 'Unpin tile' : 'Pin tile'}">&#128205;</button></div><div class="tile-meta"><span class="tile-code">${contract.number} | ${contract.suffix}${contract.suffixDescription ? ` - ${contract.suffixDescription}` : ''}</span>${contract.machineType ? `<span class="tile-machine-type">${contract.machineType}</span>` : ''}</div><div class="tile-image">${contract.image ? `<img src="${contract.image}" alt="${contract.customerName}">` : 'Image placeholder'}</div><div class="tile-times"><div class="time-block"><span>Accumulated</span><strong>${formatTime(contractSeconds(contract))}</strong></div><div class="time-block"><span>Current session</span><strong class="${running ? 'live-time' : ''}" data-live-id="${contract.id}">${running ? formatTime(Math.floor((Date.now() - contract.startedAt) / 1000)) : '00:00:00'}</strong></div></div><div class="tile-footer"><div class="tile-footer-left"><button class="tile-action edit-contract" data-id="${contract.id}" title="Edit tile" aria-label="Edit tile">&#9998;</button><button class="tile-action delete-contract" data-id="${contract.id}" title="${contract.hidden ? 'Restore tile to dashboard' : 'Remove tile from dashboard'}" aria-label="${contract.hidden ? 'Restore tile to dashboard' : 'Remove tile from dashboard'}">${contract.hidden ? '&#8635;' : '&times;'}</button></div><button class="clock-button ${running ? 'is-running' : ''}" data-id="${contract.id}" type="button">${running ? 'Stop clock' : 'Start clock'}</button></div></article>`; }
const imageViewerState = { scale: 1, fitScale: 1, x: 0, y: 0, naturalWidth: 0, naturalHeight: 0 };
function openImageViewer(src) { const img = $('#image-viewer-img'); const onReady = () => { imageViewerState.naturalWidth = img.naturalWidth; imageViewerState.naturalHeight = img.naturalHeight; zoomToFit(); }; img.onload = onReady; img.src = src; if (img.complete && img.naturalWidth) onReady(); $('#image-viewer-modal').classList.remove('is-hidden'); }
function closeImageViewer() { $('#image-viewer-modal').classList.add('is-hidden'); }
function applyImageTransform() { $('#image-viewer-img').style.transform = `translate(${imageViewerState.x}px, ${imageViewerState.y}px) scale(${imageViewerState.scale})`; }
function zoomToFit() { const viewport = $('#image-viewer-viewport'); const rect = viewport.getBoundingClientRect(); const fit = Math.min(rect.width / imageViewerState.naturalWidth, rect.height / imageViewerState.naturalHeight, 1) || 1; imageViewerState.fitScale = fit; imageViewerState.scale = fit; imageViewerState.x = 0; imageViewerState.y = 0; applyImageTransform(); }
function zoomBy(factor) { imageViewerState.scale = Math.min(4, Math.max(imageViewerState.fitScale, imageViewerState.scale * factor)); applyImageTransform(); }
function enableImagePan(img) { let panning = false; let startX; let startY; let originX; let originY; img.addEventListener('pointerdown', (event) => { panning = true; startX = event.clientX; startY = event.clientY; originX = imageViewerState.x; originY = imageViewerState.y; img.setPointerCapture(event.pointerId); }); img.addEventListener('pointermove', (event) => { if (!panning) return; imageViewerState.x = originX + (event.clientX - startX); imageViewerState.y = originY + (event.clientY - startY); applyImageTransform(); }); img.addEventListener('pointerup', (event) => { panning = false; img.releasePointerCapture(event.pointerId); }); }
function toggleClock(id) { const contract = state.contracts.find((item) => item.id === id); if (!contract) return; if (isDateCommitted(TODAY) && !state.adminMode) { showToast("Today's times are committed — enable admin mode to make changes"); return; } if (contract.startedAt) { recordSession(contract, contract.startedAt, Date.now()); contract.startedAt = null; showToast(`${contract.customerName} stopped and saved`); } else { const runningContract = state.contracts.find((item) => item.id !== id && item.startedAt); if (runningContract) { recordSession(runningContract, runningContract.startedAt, Date.now()); runningContract.startedAt = null; } contract.startedAt = Date.now(); showToast(runningContract ? `${runningContract.customerName} stopped; ${contract.customerName} is now running` : `${contract.customerName} is now running`); } saveState(); renderContracts(); renderEditTimes(); }
function togglePin(id) { const contract = state.contracts.find((item) => item.id === id); contract.pinned = !contract.pinned; saveState(); renderContracts(); showToast(contract.pinned ? 'Tile pinned in place' : 'Tile can be rearranged'); }
function toggleTileVisibility(id) { const contract = state.contracts.find((item) => item.id === id); if (!contract) return; contract.hidden = !contract.hidden; saveState(); renderContracts(); showToast(contract.hidden ? 'Tile removed from dashboard' : 'Tile restored to dashboard'); }
function updateMetrics() { const total = state.contracts.reduce((sum, contract) => sum + todaySessionSeconds(contract.id) + (contract.startedAt ? Math.floor((Date.now() - contract.startedAt) / 1000) : 0), 0); const active = state.contracts.filter((contract) => contract.startedAt).length; const nonWorking = state.workingTimes.reduce((sum, entry) => sum + entry.breaks.reduce((breakTotal, breakItem) => breakTotal + scheduleBreakSeconds(breakItem), 0), 0); const activeCount = $('#active-count'); $('#tracked-total').textContent = formatTime(total); if (activeCount) activeCount.textContent = active; $('#non-working-total').textContent = formatTime(nonWorking, false); }
function enableDrag(tile) { tile.addEventListener('dragstart', () => tile.classList.add('is-dragging')); tile.addEventListener('dragend', () => { tile.classList.remove('is-dragging'); const ids = [...document.querySelectorAll('.tile')].map((item) => item.dataset.id); state.order = ids.concat(state.order.filter((id) => !ids.includes(id))); saveState(); }); tile.addEventListener('dragover', (event) => { event.preventDefault(); if (tile.classList.contains('is-pinned')) return; const dragging = document.querySelector('.is-dragging'); if (dragging && dragging !== tile) { const box = tile.getBoundingClientRect(); tile.parentNode.insertBefore(dragging, event.clientY < box.top + box.height / 2 ? tile : tile.nextSibling); } }); }
function renderWorkingTimes() { const heading = $('#timeline-heading'); heading.innerHTML = Array.from({ length: 24 }, (_, hour) => `<span>${hour.toString().padStart(2, '0')}:00</span>`).join(''); const rows = $('#working-time-rows'); $('#empty-state').classList.toggle('is-hidden', state.workingTimes.length > 0); rows.innerHTML = state.workingTimes.map(workingTimeRowTemplate).join(''); rows.querySelectorAll('[data-entry-field]').forEach((input) => input.addEventListener('change', () => { const entry = state.workingTimes.find((item) => item.id === input.dataset.entryId); entry[input.dataset.entryField] = input.value; saveState(); renderWorkingTimes(); updateMetrics(); })); rows.querySelectorAll('.remove-user').forEach((button) => button.addEventListener('click', () => removeWorkingTimeEntry(button.dataset.entryId))); rows.querySelectorAll('.edit-break').forEach((button) => { button.addEventListener('click', () => { if (button.dataset.longPressed) { delete button.dataset.longPressed; return; } openScheduleModal(button.dataset.entryId); }); enableBreakLongPress(button); }); rows.querySelectorAll('.add-break').forEach((button) => button.addEventListener('click', () => openScheduleModal(button.dataset.entryId))); rows.querySelectorAll('.schedule-handle').forEach(enableScheduleHandle); }
function enableBreakLongPress(breakBlock) { let pressTimer; let longPressed = false; const cancelPress = () => { clearTimeout(pressTimer); }; breakBlock.addEventListener('pointerdown', (event) => { if (event.target.closest('.schedule-handle')) return; longPressed = false; pressTimer = setTimeout(() => { longPressed = true; showConfirm('Delete this break?').then((confirmed) => { if (confirmed) deleteBreak(breakBlock.dataset.entryId, breakBlock.dataset.breakId); else breakBlock.dataset.longPressed = 'true'; }); }, 700); }); breakBlock.addEventListener('pointerup', () => { clearTimeout(pressTimer); if (longPressed) breakBlock.dataset.longPressed = 'true'; }); breakBlock.addEventListener('pointerleave', cancelPress); breakBlock.addEventListener('pointercancel', cancelPress); }
function deleteBreak(entryId, breakId) { const entry = state.workingTimes.find((item) => item.id === entryId); if (!entry) return; entry.breaks = entry.breaks.filter((breakItem) => breakItem.id !== breakId); saveState(); renderWorkingTimes(); updateMetrics(); showToast('Break deleted'); }
function updateDragTooltip(handle, target, event) { const tooltip = $('#drag-tooltip'); tooltip.textContent = `${handle.dataset.handle === 'start' ? 'Start' : 'End'}: ${target[handle.dataset.handle]}`; tooltip.style.left = `${event.clientX + 12}px`; tooltip.style.top = `${event.clientY - 38}px`; tooltip.classList.remove('is-hidden'); }
function hideDragTooltip() { $('#drag-tooltip').classList.add('is-hidden'); }
function enableScheduleHandle(handle) { let resizing = false; let startX; let originalStart; let originalEnd; const entry = state.workingTimes.find((item) => item.id === handle.dataset.entryId); const breakItem = entry?.breaks.find((item) => item.id === handle.dataset.breakId); const target = breakItem || entry; handle.title = `Drag to adjust ${handle.dataset.handle} time`; handle.addEventListener('pointerdown', (event) => { event.preventDefault(); event.stopPropagation(); resizing = true; startX = event.clientX; originalStart = timeToMinutes(target.start); originalEnd = timeToMinutes(target.end); handle.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); updateDragTooltip(handle, target, event); }); handle.addEventListener('pointermove', (event) => { if (!resizing) return; const lane = handle.closest('.timeline-lane'); const delta = Math.round(((event.clientX - startX) / lane.getBoundingClientRect().width * 1440) / 5) * 5; if (handle.dataset.handle === 'start') target.start = minutesToTime(Math.min(originalEnd - 5, Math.max(0, originalStart + delta))); else target.end = minutesToTime(Math.max(originalStart + 5, Math.min(1440, originalEnd + delta))); const block = handle.closest(breakItem ? '.break-block' : '.scheduled-block'); const start = timeToMinutes(target.start); const end = timeToMinutes(target.end); block.style.left = `${start / 1440 * 100}%`; block.style.width = `${Math.max(0, end - start) / 1440 * 100}%`; if (!breakItem) { const row = handle.closest('.schedule-row'); row.querySelector(`[data-entry-field="start"]`).value = target.start; row.querySelector(`[data-entry-field="end"]`).value = target.end; } updateDragTooltip(handle, target, event); }); handle.addEventListener('pointerup', (event) => { if (!resizing) return; resizing = false; handle.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); hideDragTooltip(); saveState(); renderWorkingTimes(); updateMetrics(); }); handle.addEventListener('pointercancel', () => { if (!resizing) return; resizing = false; document.body.classList.remove('is-resizing'); hideDragTooltip(); }); }
function workingTimeRowTemplate(entry) { const user = state.users.find((item) => item.id === entry.userId); const name = user?.name || 'Unknown user'; const start = timeToMinutes(entry.start); const end = timeToMinutes(entry.end); const workWidth = Math.max(0, end - start) / 1440 * 100; return `<div class="schedule-row"><div class="user-cell"><div class="user-name-line"><strong class="working-time-name">${name}</strong><button class="remove-user" data-entry-id="${entry.id}" type="button" title="Remove ${name}" aria-label="Remove ${name}">&times;</button></div><span><input type="time" data-entry-id="${entry.id}" data-entry-field="start" value="${entry.start}"> - <input type="time" data-entry-id="${entry.id}" data-entry-field="end" value="${entry.end}"></span><button class="add-break" data-entry-id="${entry.id}" type="button" title="Manage breaks for ${name}">+ break</button></div><div class="timeline-lane"><div class="scheduled-block" style="left:${start / 1440 * 100}%;width:${workWidth}%"><button class="schedule-handle start-handle" data-entry-id="${entry.id}" data-handle="start" type="button" title="Drag to adjust start time" aria-label="Adjust ${name} start time"></button><button class="schedule-handle end-handle" data-entry-id="${entry.id}" data-handle="end" type="button" title="Drag to adjust end time" aria-label="Adjust ${name} end time"></button></div>${entry.breaks.map((breakItem) => `<div class="break-block edit-break" data-entry-id="${entry.id}" data-break-id="${breakItem.id}" style="left:${timeToMinutes(breakItem.start) / 1440 * 100}%;width:${Math.max(1, timeToMinutes(breakItem.end) - timeToMinutes(breakItem.start)) / 1440 * 100}%" title="Edit ${breakItem.type}: ${breakItem.start} - ${breakItem.end}"><button class="schedule-handle start-handle break-handle" data-entry-id="${entry.id}" data-break-id="${breakItem.id}" data-handle="start" type="button" title="Drag to adjust break start time" aria-label="Adjust ${breakItem.type} start time"></button><button class="schedule-handle end-handle break-handle" data-entry-id="${entry.id}" data-break-id="${breakItem.id}" data-handle="end" type="button" title="Drag to adjust break end time" aria-label="Adjust ${breakItem.type} end time"></button></div>`).join('')}</div></div>`; }
function removeUser(id) { if (id === 'jordan') { showToast('Jordan Reed is the signed-in user'); return; } state.users = state.users.filter((user) => user.id !== id); state.workingTimes = state.workingTimes.filter((entry) => entry.userId !== id); saveState(); renderWorkingTimes(); renderUserList(); updateMetrics(); showToast('User removed'); }
function removeWorkingTimeEntry(entryId) { state.workingTimes = state.workingTimes.filter((entry) => entry.id !== entryId); saveState(); renderWorkingTimes(); updateMetrics(); showToast('Working time entry removed'); }
let editingScheduleEntryId = null;
let scheduleBreaksDraft = [];
let editingContractId = null;
function customerOptionsHtml(selected) { return '<option value="">Select customer</option>' + state.customers.map((name) => `<option value="${name}" ${name === selected ? 'selected' : ''}>${name}</option>`).join(''); }
function contractNumberOptionsHtml(selected) { const numbers = [...new Set(state.contractInfo.map((record) => record.number).filter(Boolean))]; return '<option value="">Select contract number</option>' + numbers.map((num) => `<option value="${num}" ${num === selected ? 'selected' : ''}>${num}</option>`).join(''); }
function suffixOptionsHtmlForContractNumber(number, selected) { const record = state.contractInfo.find((item) => item.number === number); const suffixes = record?.suffixes || []; return '<option value="">Select suffix</option>' + suffixes.map((suffix) => `<option value="${suffix.letter}" ${suffix.letter === selected ? 'selected' : ''}>${suffix.letter}</option>`).join(''); }
function refreshContractSuffixOptions(selected = '') { $('#contract-suffix').innerHTML = suffixOptionsHtmlForContractNumber($('#contract-number').value, selected); }
function refreshContractDerivedFields() { const record = state.contractInfo.find((item) => item.number === $('#contract-number').value); $('#contract-machine-type').value = record?.machineType || ''; const suffix = record?.suffixes.find((item) => item.letter === $('#contract-suffix').value); $('#contract-suffix-description').value = suffix?.description || ''; }
function openContractModal(contractId = null) { editingContractId = contractId; const contract = contractId ? state.contracts.find((item) => item.id === contractId) : null; $('#contract-modal-title').textContent = contract ? 'Edit tile' : 'Add tile'; $('#contract-submit').innerHTML = contract ? 'Save changes' : '<span>+</span> Add tile'; $('#contract-customer-name').innerHTML = customerOptionsHtml(contract?.customerName || ''); $('#contract-number').innerHTML = contractNumberOptionsHtml(contract?.number || ''); refreshContractSuffixOptions(contract?.suffix || ''); $('#contract-suffix-description').value = contract?.suffixDescription || ''; $('#contract-machine-type').value = contract?.machineType || ''; $('#contract-image').value = ''; $('#contract-image-preview').innerHTML = contract?.image ? `<img src="${contract.image}" alt="Current image"><span>Current image — choose a file to replace it</span>` : ''; $('#contract-modal').classList.remove('is-hidden'); $('#contract-customer-name').focus(); }
function renderScheduleBreakRows() { const container = $('#schedule-break-rows'); container.innerHTML = scheduleBreaksDraft.map((brk, index) => { const isLast = index === scheduleBreaksDraft.length - 1; return `<div class="form-row break-row"><label>Break starts<input type="time" data-break-index="${index}" data-break-field="start" value="${brk.start}"></label><label>Break ends<input type="time" data-break-index="${index}" data-break-field="end" value="${brk.end}"></label><button class="break-row-action ${isLast ? 'add-break-row' : 'remove-break-row'}" data-break-index="${index}" type="button" title="${isLast ? 'Add another break' : 'Remove this break'}" aria-label="${isLast ? 'Add another break' : 'Remove this break'}">${isLast ? '&#43;' : '&times;'}</button></div>`; }).join(''); container.querySelectorAll('[data-break-field]').forEach((input) => input.addEventListener('change', () => { scheduleBreaksDraft[Number(input.dataset.breakIndex)][input.dataset.breakField] = input.value; })); container.querySelectorAll('.add-break-row').forEach((button) => button.addEventListener('click', () => { scheduleBreaksDraft.push({ start: '12:30', end: '13:05' }); renderScheduleBreakRows(); })); container.querySelectorAll('.remove-break-row').forEach((button) => button.addEventListener('click', () => { scheduleBreaksDraft.splice(Number(button.dataset.breakIndex), 1); renderScheduleBreakRows(); })); }
function openScheduleModal(entryId = null) { editingScheduleEntryId = entryId; const entry = state.workingTimes.find((item) => item.id === entryId); const user = entry ? state.users.find((item) => item.id === entry.userId) : null; $('#schedule-modal-title').textContent = user ? `Edit ${user.name}` : 'Add user'; const select = $('#schedule-user-name'); const assignedIds = new Set(state.workingTimes.map((item) => item.userId)); const availableUsers = state.users.filter((item) => item.id === entry?.userId || !assignedIds.has(item.id)); select.innerHTML = '<option value="">Select user</option>' + availableUsers.map((item) => `<option value="${item.id}" ${entry && item.id === entry.userId ? 'selected' : ''}>${item.name}</option>`).join(''); select.disabled = Boolean(entry); $('#schedule-start').value = entry?.start || '06:00'; $('#schedule-end').value = entry?.end || '15:00'; scheduleBreaksDraft = entry && entry.breaks.length ? entry.breaks.map((brk) => ({ id: brk.id, start: brk.start, end: brk.end })) : [{ start: '12:30', end: '13:05' }]; renderScheduleBreakRows(); $('#schedule-modal').classList.remove('is-hidden'); $('#schedule-user-name').focus(); }
function closeScheduleModal() { $('#schedule-modal').classList.add('is-hidden'); $('#schedule-form').reset(); $('#schedule-user-name').disabled = false; editingScheduleEntryId = null; scheduleBreaksDraft = []; }
function saveSchedule(event) { event.preventDefault(); const formData = new FormData(event.currentTarget); const existingEntry = editingScheduleEntryId ? state.workingTimes.find((item) => item.id === editingScheduleEntryId) : null; const targetUserId = existingEntry ? existingEntry.userId : formData.get('userId'); const start = formData.get('start'); const end = formData.get('end'); if (!targetUserId) { showToast('Select a user'); return; } if (timeToMinutes(end) <= timeToMinutes(start)) { showToast('End time must be after start time'); return; } for (const brk of scheduleBreaksDraft) { if (timeToMinutes(brk.end) <= timeToMinutes(brk.start)) { showToast('Break end times must be after start times'); return; } } const breaks = scheduleBreaksDraft.map((brk, index) => ({ id: brk.id || `break-${Date.now()}-${index}`, type: 'Break', start: brk.start, end: brk.end })); if (existingEntry) { existingEntry.start = start; existingEntry.end = end; existingEntry.breaks = breaks; } else { state.workingTimes.push({ id: `wt-${Date.now()}`, userId: targetUserId, start, end, breaks }); } saveState(); renderWorkingTimes(); updateMetrics(); closeScheduleModal(); showToast(existingEntry ? 'Working times updated' : 'Working times added'); }
function closeContractModal() { $('#contract-modal').classList.add('is-hidden'); $('#contract-form').reset(); $('#contract-image-preview').innerHTML = ''; editingContractId = null; }
function saveContract(event) { event.preventDefault(); const formData = new FormData(event.currentTarget); const customerName = formData.get('customerName').trim(); const number = formData.get('number').trim(); const suffix = formData.get('suffix').trim(); const suffixDescription = formData.get('suffixDescription').trim(); const machineType = formData.get('machineType'); const imageFile = formData.get('image'); const contractId = editingContractId; const finishSaveContract = (image) => { if (contractId) { const contract = state.contracts.find((item) => item.id === contractId); contract.customerName = customerName; contract.number = number; contract.suffix = suffix; contract.suffixDescription = suffixDescription; contract.machineType = machineType; if (image) contract.image = image; } else { const id = `contract-${Date.now()}`; state.contracts.push({ id, customerName, number, suffix, suffixDescription, machineType, image, startedAt: null, pinned: false, hidden: false }); state.order.push(id); state.editSessions[id] = [{ id: `session-${id}-1`, date: EDIT_TIMES_DATE, start: '09:00', end: '09:30' }]; } const saved = saveState(); renderContracts(); renderEditTimes(); closeContractModal(); showToast(saved ? (contractId ? 'Tile updated' : 'Tile added to dashboard') : 'Changes made, but could not be saved (storage limit reached — try a smaller image)'); }; const proceedWithSave = () => { if (imageFile && imageFile.size) { const reader = new FileReader(); reader.onload = () => finishSaveContract(reader.result); reader.readAsDataURL(imageFile); } else { finishSaveContract(null); } }; const isDuplicate = !contractId && state.contracts.some((item) => item.customerName === customerName && item.number === number && item.suffix === suffix); if (isDuplicate) { showConfirm('A tile for this customer, contract number and suffix already exists. Add it anyway?').then((confirmed) => { if (confirmed) proceedWithSave(); }); } else { proceedWithSave(); } }
function machineTypeOptionsHtml(selected) { return '<option value="">Select machine type</option>' + state.machineTypes.map((type) => `<option value="${type}" ${type === selected ? 'selected' : ''}>${type}</option>`).join(''); }
function switchListTab(tabId) { document.querySelectorAll('.modal-tab').forEach((tab) => tab.classList.toggle('is-active', tab.dataset.listTab === tabId)); document.querySelectorAll('[data-list-panel]').forEach((panel) => panel.classList.toggle('is-hidden', panel.dataset.listPanel !== tabId)); }
function openListsModal(tabId = 'machine-type') { $('#lists-modal').classList.remove('is-hidden'); switchListTab(tabId); renderMachineTypeList(); renderSuffixDescriptionList(); renderCustomerList(); renderUserList(); renderCostCentreList(); renderDefaultWorkingTimes(); }
function goToContractInformation() { closeContractModal(); $('#nav-setup-children').classList.remove('is-hidden'); $('#nav-setup-toggle').setAttribute('aria-expanded', 'true'); $('#nav-setup-toggle').classList.add('is-expanded'); document.querySelector('[data-view="contract-information"]').click(); showToast('Add or edit the missing details, then reopen Add tile'); }
function enableFieldLongPress(selector, callback) { const element = $(selector); if (!element) return; let pressTimer; const cancelPress = () => clearTimeout(pressTimer); element.addEventListener('pointerdown', () => { pressTimer = setTimeout(callback, 700); }); element.addEventListener('pointerup', cancelPress); element.addEventListener('pointerleave', cancelPress); element.addEventListener('pointercancel', cancelPress); element.addEventListener('change', cancelPress); element.addEventListener('blur', cancelPress); }
function closeListsModal() { $('#lists-modal').classList.add('is-hidden'); $('#machine-type-input').value = ''; $('#suffix-description-input').value = ''; $('#customer-input').value = ''; $('#cost-centre-input').value = ''; if (!$('#contract-modal').classList.contains('is-hidden')) { const customerSelect = $('#contract-customer-name'); customerSelect.innerHTML = customerOptionsHtml(customerSelect.value); } }
function levenshteinDistance(a, b) { const rows = a.length + 1; const cols = b.length + 1; const dp = Array.from({ length: rows }, () => new Array(cols).fill(0)); for (let i = 0; i < rows; i += 1) dp[i][0] = i; for (let j = 0; j < cols; j += 1) dp[0][j] = j; for (let i = 1; i < rows; i += 1) { for (let j = 1; j < cols; j += 1) { dp[i][j] = a[i - 1] === b[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]); } } return dp[rows - 1][cols - 1]; }
function textSimilarity(a, b) { const distance = levenshteinDistance(a.toLowerCase(), b.toLowerCase()); const maxLength = Math.max(a.length, b.length) || 1; return 1 - distance / maxLength; }
function findSimilarEntry(value, list, threshold = 0.75) { let best = null; let bestScore = 0; list.forEach((item) => { const score = textSimilarity(value, item); if (score > bestScore) { bestScore = score; best = item; } }); return bestScore >= threshold ? best : null; }
function renderSuffixDescriptionList() { const list = $('#suffix-description-list'); list.innerHTML = state.suffixDescriptions.length ? state.suffixDescriptions.map((desc) => `<li>${desc}<button class="remove-list-item" data-suffix-desc="${desc}" type="button" aria-label="Remove ${desc}">&times;</button></li>`).join('') : '<li class="list-empty">No suffix descriptions yet.</li>'; list.querySelectorAll('.remove-list-item').forEach((button) => button.addEventListener('click', () => removeSuffixDescription(button.dataset.suffixDesc))); }
function addSuffixDescription(event) { event.preventDefault(); const input = $('#suffix-description-input'); const value = input.value.trim(); if (!value) return; const exactMatch = state.suffixDescriptions.find((item) => item.toLowerCase() === value.toLowerCase()); if (exactMatch) { showToast('That suffix description already exists'); input.value = ''; return; } const commit = () => { state.suffixDescriptions.push(value); input.value = ''; saveState(); renderSuffixDescriptionList(); }; const similar = findSimilarEntry(value, state.suffixDescriptions); if (similar) { showConfirm(`This looks similar to "${similar}". Add it anyway?`).then((confirmed) => { if (confirmed) commit(); }); } else { commit(); } }
function removeSuffixDescription(value) { state.suffixDescriptions = state.suffixDescriptions.filter((item) => item !== value); saveState(); renderSuffixDescriptionList(); }
function renderMachineTypeList() { const list = $('#machine-type-list'); list.innerHTML = state.machineTypes.length ? state.machineTypes.map((type) => `<li>${type}<button class="remove-list-item" data-type="${type}" type="button" aria-label="Remove ${type}">&times;</button></li>`).join('') : '<li class="list-empty">No machine types yet.</li>'; list.querySelectorAll('.remove-list-item').forEach((button) => button.addEventListener('click', () => removeMachineType(button.dataset.type))); }
function addMachineType(event) { event.preventDefault(); const input = $('#machine-type-input'); const value = input.value.trim(); if (!value || state.machineTypes.includes(value)) { input.value = ''; return; } state.machineTypes.push(value); input.value = ''; saveState(); renderMachineTypeList(); }
function removeMachineType(type) { state.machineTypes = state.machineTypes.filter((item) => item !== type); saveState(); renderMachineTypeList(); }
function renderCustomerList() { const list = $('#customer-list'); list.innerHTML = state.customers.length ? state.customers.map((name) => `<li>${name}<button class="remove-list-item" data-customer="${name}" type="button" aria-label="Remove ${name}">&times;</button></li>`).join('') : '<li class="list-empty">No customers yet.</li>'; list.querySelectorAll('.remove-list-item').forEach((button) => button.addEventListener('click', () => removeCustomer(button.dataset.customer))); }
function addCustomer(event) { event.preventDefault(); const input = $('#customer-input'); const value = input.value.trim(); if (!value || state.customers.includes(value)) { input.value = ''; return; } state.customers.push(value); input.value = ''; saveState(); renderCustomerList(); }
function removeCustomer(name) { state.customers = state.customers.filter((item) => item !== name); saveState(); renderCustomerList(); }
function renderCostCentreList() { const list = $('#cost-centre-list'); list.innerHTML = state.costCentres.length ? state.costCentres.map((name) => `<li>${name}<button class="remove-list-item" data-cost-centre="${name}" type="button" aria-label="Remove ${name}">&times;</button></li>`).join('') : '<li class="list-empty">No cost centres yet.</li>'; list.querySelectorAll('.remove-list-item').forEach((button) => button.addEventListener('click', () => removeCostCentre(button.dataset.costCentre))); }
function addCostCentre(event) { event.preventDefault(); const input = $('#cost-centre-input'); const value = input.value.trim(); if (!value || state.costCentres.includes(value)) { input.value = ''; return; } state.costCentres.push(value); input.value = ''; saveState(); renderCostCentreList(); }
function removeCostCentre(name) { state.costCentres = state.costCentres.filter((item) => item !== name); saveState(); renderCostCentreList(); }
function userTypeOptionsHtml(selected) { return ['admin', 'manager', 'user'].map((type) => `<option value="${type}" ${type === selected ? 'selected' : ''}>${type.charAt(0).toUpperCase() + type.slice(1)}</option>`).join(''); }
function costCentreOptionsHtml(selected) { return '<option value="">Select cost centre</option>' + state.costCentres.map((name) => `<option value="${name}" ${name === selected ? 'selected' : ''}>${name}</option>`).join(''); }
function userListRowTemplate(user) { return `<tr><td><input type="text" data-user-id="${user.id}" data-user-list-field="name" value="${user.name}" placeholder="e.g. Alex Morgan"></td><td><input type="email" data-user-id="${user.id}" data-user-list-field="email" value="${user.email || ''}" placeholder="e.g. alex@example.com"></td><td><select data-user-id="${user.id}" data-user-list-field="userType">${userTypeOptionsHtml(user.userType || 'user')}</select></td><td><select data-user-id="${user.id}" data-user-list-field="costCentre">${costCentreOptionsHtml(user.costCentre || '')}</select></td><td><button class="delete-row" data-user-id="${user.id}" type="button" title="Remove user" aria-label="Remove ${user.name}">&times;</button></td></tr>`; }
function renderUserList() { const rows = $('#user-rows'); if (!rows) return; rows.innerHTML = state.users.length ? state.users.map(userListRowTemplate).join('') : '<tr><td colspan="5" class="list-empty">No users yet.</td></tr>'; rows.querySelectorAll('[data-user-list-field]').forEach((input) => input.addEventListener('change', () => { const user = state.users.find((item) => item.id === input.dataset.userId); if (!user) return; user[input.dataset.userListField] = input.value.trim ? input.value.trim() : input.value; saveState(); renderUserList(); renderWorkingTimes(); })); rows.querySelectorAll('.delete-row').forEach((button) => button.addEventListener('click', () => removeUser(button.dataset.userId))); }
function renderDefaultWorkingTimes() { $('#default-wt-start').value = state.defaultWorkingTimes.start; $('#default-wt-end').value = state.defaultWorkingTimes.end; $('#default-wt-break1-start').value = state.defaultWorkingTimes.breaks[0].start; $('#default-wt-break1-end').value = state.defaultWorkingTimes.breaks[0].end; $('#default-wt-break2-start').value = state.defaultWorkingTimes.breaks[1].start; $('#default-wt-break2-end').value = state.defaultWorkingTimes.breaks[1].end; }
function saveDefaultWorkingTimeField(path, value) { if (path[0] === 'break') { state.defaultWorkingTimes.breaks[path[1]][path[2]] = value; } else { state.defaultWorkingTimes[path[0]] = value; } saveState(); }
function addUserFromList() { const id = `user-${Date.now()}`; state.users.push({ id, name: '', email: '', userType: 'user', costCentre: '' }); state.workingTimes.push({ id: `wt-${id}`, userId: id, start: state.defaultWorkingTimes.start, end: state.defaultWorkingTimes.end, breaks: state.defaultWorkingTimes.breaks.map((brk, index) => ({ id: `break-${id}-${index}`, type: 'Break', start: brk.start, end: brk.end })) }); saveState(); renderUserList(); renderWorkingTimes(); }
function renderContractInfo() { const rows = $('#contract-info-rows'); if (!rows) return; $('#contract-info-empty').classList.toggle('is-hidden', state.contractInfo.length > 0); rows.innerHTML = state.contractInfo.map(contractInfoRowTemplate).join(''); rows.querySelectorAll('[data-info-field]').forEach((input) => input.addEventListener('change', () => { const record = state.contractInfo.find((item) => item.id === input.dataset.infoId); record[input.dataset.infoField] = input.value.trim(); saveState(); renderContractInfo(); })); rows.querySelectorAll('[data-suffix-field]').forEach((input) => input.addEventListener('change', () => { const record = state.contractInfo.find((item) => item.id === input.dataset.parentId); const suffix = record?.suffixes.find((item) => item.id === input.dataset.suffixId); if (!suffix) return; let value = input.value.trim(); if (input.dataset.suffixField === 'letter') value = value.toUpperCase(); suffix[input.dataset.suffixField] = value; saveState(); renderContractInfo(); })); rows.querySelectorAll('.expand-suffixes').forEach((button) => button.addEventListener('click', () => toggleContractInfoExpand(button.dataset.infoId))); rows.querySelectorAll('.add-suffix-row').forEach((button) => button.addEventListener('click', () => addSuffixRow(button.dataset.parentId))); rows.querySelectorAll('.remove-suffix-row').forEach((button) => button.addEventListener('click', () => { showConfirm('Remove this suffix?').then((confirmed) => { if (confirmed) removeSuffixRow(button.dataset.parentId, button.dataset.suffixId); }); })); rows.querySelectorAll('.delete-row:not(.remove-suffix-row)').forEach((button) => button.addEventListener('click', () => { showConfirm('Remove this contract information entry?').then((confirmed) => { if (confirmed) removeContractInfo(button.dataset.infoId); }); })); }
function contractInfoLinkCell(record, field) { return `<div class="link-cell"><input type="url" data-info-id="${record.id}" data-info-field="${field}" value="${record[field]}" placeholder="https://..."/>${record[field] ? `<a class="open-link" href="${record[field]}" target="_blank" rel="noopener noreferrer" title="Open link" aria-label="Open link">&#8599;</a>` : ''}</div>`; }
function contractInfoRowTemplate(record) { const parentRow = `<tr class="contract-info-row"><td><input type="text" data-info-id="${record.id}" data-info-field="number" value="${record.number}" placeholder="e.g. CNT-1048"></td><td><select data-info-id="${record.id}" data-info-field="machineType">${machineTypeOptionsHtml(record.machineType)}</select></td><td><select class="force-uppercase" data-info-id="${record.id}" data-info-field="customerName">${customerOptionsHtml(record.customerName)}</select></td><td>${contractInfoLinkCell(record, 'oneDriveLink')}</td><td>${contractInfoLinkCell(record, 'orderConfirmationLink')}</td><td><button class="expand-suffixes ${record.expanded ? 'is-expanded' : ''}" data-info-id="${record.id}" type="button" title="${record.expanded ? 'Hide suffixes' : 'Show suffixes'}" aria-label="${record.expanded ? 'Hide suffixes' : 'Show suffixes'}"><span class="nav-chevron"></span></button></td><td><button class="delete-row" data-info-id="${record.id}" type="button" title="Remove entry" aria-label="Remove entry">&times;</button></td></tr>`; const childRow = `<tr class="suffix-row-container ${record.expanded ? '' : 'is-hidden'}"><td colspan="7">${suffixSubtableTemplate(record)}</td></tr>`; return parentRow + childRow; }
function suffixSubtableTemplate(record) { const suffixRows = record.suffixes.map((suffix) => suffixRowTemplate(record.id, suffix)).join('') || '<tr><td colspan="3" class="suffix-empty">No suffixes yet.</td></tr>'; return `<div class="suffix-subtable"><table><thead><tr><th class="col-narrow">Suffix letter</th><th class="col-suffix-desc">Description</th><th class="col-icon"></th></tr></thead><tbody>${suffixRows}</tbody></table><button class="add-button add-suffix-row" data-parent-id="${record.id}" type="button">+ Add suffix</button></div>`; }
function suffixDescriptionOptionsHtml(selected) { return '<option value="">Select suffix description</option>' + state.suffixDescriptions.map((desc) => `<option value="${desc}" ${desc === selected ? 'selected' : ''}>${desc}</option>`).join(''); }
function suffixRowTemplate(parentId, suffix) { return `<tr><td><input type="text" class="force-uppercase" data-parent-id="${parentId}" data-suffix-id="${suffix.id}" data-suffix-field="letter" value="${suffix.letter}" placeholder="e.g. A"></td><td><select data-parent-id="${parentId}" data-suffix-id="${suffix.id}" data-suffix-field="description">${suffixDescriptionOptionsHtml(suffix.description)}</select></td><td><button class="delete-row remove-suffix-row" data-parent-id="${parentId}" data-suffix-id="${suffix.id}" type="button" title="Remove suffix" aria-label="Remove suffix">&times;</button></td></tr>`; }
function toggleContractInfoExpand(id) { const record = state.contractInfo.find((item) => item.id === id); if (!record) return; record.expanded = !record.expanded; saveState(); renderContractInfo(); }
function addSuffixRow(parentId) { const record = state.contractInfo.find((item) => item.id === parentId); if (!record) return; record.suffixes.push({ id: `suffix-${Date.now()}`, letter: '', description: '' }); record.expanded = true; saveState(); renderContractInfo(); }
function removeSuffixRow(parentId, suffixId) { const record = state.contractInfo.find((item) => item.id === parentId); if (!record) return; record.suffixes = record.suffixes.filter((item) => item.id !== suffixId); saveState(); renderContractInfo(); }
function addContractInfo() { const id = `info-${Date.now()}`; state.contractInfo.push({ id, number: '', machineType: '', customerName: '', oneDriveLink: '', orderConfirmationLink: '', expanded: true, suffixes: [] }); saveState(); renderContractInfo(); }
function removeContractInfo(id) { state.contractInfo = state.contractInfo.filter((item) => item.id !== id); saveState(); renderContractInfo(); showToast('Contract information entry removed'); }
let confirmResolve = null;
function showConfirm(message, confirmLabel = 'Confirm') { return new Promise((resolve) => { confirmResolve = resolve; $('#confirm-modal-message').textContent = message; $('#confirm-modal-confirm').textContent = confirmLabel; $('#confirm-modal').classList.remove('is-hidden'); }); }
function closeConfirmModal(result) { $('#confirm-modal').classList.add('is-hidden'); if (confirmResolve) { confirmResolve(result); confirmResolve = null; } }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('is-visible'), 2300); }
function commitTimes() { const date = $('#edit-times-date').value; if (isDateCommitted(date)) { if (!state.adminMode) return; state.committedDates = state.committedDates.filter((item) => item !== date); saveState(); renderEditTimes(); showToast(`Commit removed for ${date}`); return; } state.committedDates.push(date); saveState(); renderEditTimes(); showToast(`Times committed for ${date}`); }
function updateCommittedUi() { const date = $('#edit-times-date').value; const committed = isDateCommitted(date); const locked = committed && !state.adminMode; $('#admin-mode-toggle').checked = state.adminMode; $('#committed-badge').classList.toggle('is-hidden', !committed); $('#edit-times-card').classList.toggle('is-locked', locked); const commitButton = $('#commit-times'); if (committed && state.adminMode) { commitButton.textContent = 'Uncommit'; commitButton.disabled = false; } else if (committed) { commitButton.textContent = 'Committed'; commitButton.disabled = true; } else { commitButton.textContent = 'Commit'; commitButton.disabled = false; } }
function pauseRunningContract(contract) { if (!contract?.startedAt) return; recordSession(contract, contract.startedAt, Date.now()); contract.startedAt = null; }
function handleBreakState() { const breakItem = currentBreak(); if (breakItem && !state.breakState) { const runningContract = state.contracts.find((contract) => contract.startedAt); if (runningContract) { pauseRunningContract(runningContract); state.breakState = { contractId: runningContract.id }; saveState(); showToast(`${runningContract.customerName} paused for break`); } } else if (!breakItem && state.breakState) { const pausedContract = state.contracts.find((contract) => contract.id === state.breakState.contractId); if (pausedContract && !state.contracts.some((contract) => contract.startedAt)) { pausedContract.startedAt = Date.now(); showToast(`${pausedContract.customerName} resumed after break`); } state.breakState = null; saveState(); } }
function tick() { handleBreakState(); state.contracts.filter((contract) => contract.startedAt).forEach((contract) => { const live = document.querySelector(`[data-live-id="${contract.id}"]`); if (live) live.textContent = formatTime(Math.floor((Date.now() - contract.startedAt) / 1000)); }); updateMetrics(); }
document.querySelectorAll('.nav-item[data-view]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.nav-item[data-view]').forEach((item) => item.classList.toggle('is-active', item === button)); document.querySelectorAll('[data-view-panel]').forEach((panel) => panel.classList.toggle('is-hidden', panel.dataset.viewPanel !== button.dataset.view)); }));
$('#nav-setup-toggle').addEventListener('click', () => { const toggle = $('#nav-setup-toggle'); const expanded = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!expanded)); toggle.classList.toggle('is-expanded', !expanded); $('#nav-setup-children').classList.toggle('is-hidden', expanded); });
$('#add-contract').addEventListener('click', () => openContractModal()); $('#contract-form').addEventListener('submit', saveContract); $('#contract-number').addEventListener('change', () => { refreshContractSuffixOptions(); refreshContractDerivedFields(); }); $('#contract-suffix').addEventListener('change', refreshContractDerivedFields); enableFieldLongPress('#contract-customer-name', () => openListsModal('customers')); enableFieldLongPress('#contract-suffix-description', () => openListsModal('suffix-description')); enableFieldLongPress('#contract-machine-type', () => openListsModal('machine-type')); enableFieldLongPress('#contract-number', goToContractInformation); enableFieldLongPress('#contract-suffix', goToContractInformation); $('#close-contract-modal').addEventListener('click', closeContractModal); $('#cancel-contract').addEventListener('click', closeContractModal); $('#contract-modal').addEventListener('click', (event) => { if (event.target.id === 'contract-modal') closeContractModal(); }); $('#schedule-form').addEventListener('submit', saveSchedule); $('#close-schedule-modal').addEventListener('click', closeScheduleModal); $('#cancel-schedule').addEventListener('click', closeScheduleModal); $('#schedule-modal').addEventListener('click', (event) => { if (event.target.id === 'schedule-modal') closeScheduleModal(); }); $('#edit-times-date').addEventListener('change', renderEditTimes); $('#filter-contracts').addEventListener('change', renderContracts); $('#commit-times').addEventListener('click', commitTimes);
$('#admin-mode-toggle').addEventListener('change', (event) => { state.adminMode = event.target.checked; saveState(); renderEditTimes(); showToast(state.adminMode ? 'Admin mode enabled' : 'Admin mode disabled'); });
$('#add-contract-info').addEventListener('click', addContractInfo);
$('#open-lists').addEventListener('click', () => openListsModal()); $('#nav-lists-open').addEventListener('click', () => openListsModal()); $('#machine-type-panel').addEventListener('submit', addMachineType); $('#suffix-description-panel').addEventListener('submit', addSuffixDescription); $('#customers-panel').addEventListener('submit', addCustomer); $('#add-user-list').addEventListener('click', addUserFromList); $('#cost-centres-panel').addEventListener('submit', addCostCentre);
$('#default-wt-start').addEventListener('change', (event) => saveDefaultWorkingTimeField(['start'], event.target.value));
$('#default-wt-end').addEventListener('change', (event) => saveDefaultWorkingTimeField(['end'], event.target.value));
$('#default-wt-break1-start').addEventListener('change', (event) => saveDefaultWorkingTimeField(['break', 0, 'start'], event.target.value));
$('#default-wt-break1-end').addEventListener('change', (event) => saveDefaultWorkingTimeField(['break', 0, 'end'], event.target.value));
$('#default-wt-break2-start').addEventListener('change', (event) => saveDefaultWorkingTimeField(['break', 1, 'start'], event.target.value));
$('#default-wt-break2-end').addEventListener('change', (event) => saveDefaultWorkingTimeField(['break', 1, 'end'], event.target.value)); $('#close-lists-modal').addEventListener('click', closeListsModal); $('#lists-modal').addEventListener('click', (event) => { if (event.target.id === 'lists-modal') closeListsModal(); }); document.querySelectorAll('.modal-tab').forEach((tab) => tab.addEventListener('click', () => switchListTab(tab.dataset.listTab)));
$('#confirm-modal-cancel').addEventListener('click', () => closeConfirmModal(false)); $('#confirm-modal-confirm').addEventListener('click', () => closeConfirmModal(true)); $('#confirm-modal').addEventListener('click', (event) => { if (event.target.id === 'confirm-modal') closeConfirmModal(false); });
$('#close-image-viewer').addEventListener('click', closeImageViewer); $('#image-viewer-modal').addEventListener('click', (event) => { if (event.target.id === 'image-viewer-modal') closeImageViewer(); }); $('#image-zoom-in').addEventListener('click', () => zoomBy(1.25)); $('#image-zoom-out').addEventListener('click', () => zoomBy(1 / 1.25)); $('#image-zoom-fit').addEventListener('click', zoomToFit); $('#image-viewer-viewport').addEventListener('wheel', (event) => { event.preventDefault(); zoomBy(event.deltaY < 0 ? 1.15 : 1 / 1.15); }, { passive: false });
enableImagePan($('#image-viewer-img'));
const sidebarResize = $('.sidebar-resize'); let resizeStartX; let resizeStartWidth;
sidebarResize.addEventListener('pointerdown', (event) => { resizeStartX = event.clientX; resizeStartWidth = $('.sidebar').getBoundingClientRect().width; sidebarResize.setPointerCapture(event.pointerId); document.body.classList.add('is-resizing'); });
sidebarResize.addEventListener('pointermove', (event) => { if (!sidebarResize.hasPointerCapture(event.pointerId)) return; const width = Math.min(360, Math.max(190, resizeStartWidth + event.clientX - resizeStartX)); document.documentElement.style.setProperty('--sidebar-width', `${width}px`); localStorage.setItem(SIDEBAR_WIDTH_KEY, width); });
sidebarResize.addEventListener('pointerup', (event) => { sidebarResize.releasePointerCapture(event.pointerId); document.body.classList.remove('is-resizing'); });
renderContracts(); renderWorkingTimes(); renderEditTimes(); renderContractInfo(); setInterval(tick, 1000);
